bootenvs/ce-centos-7.3.1611.yml
bootenvs/ce-discovery.yml
bootenvs/ce-local.yml
bootenvs/ce-sledgehammer.yml
bootenvs/ce-ubuntu-16.04.yml
profiles/ce-root-access.yml
templates/ce-centos-7.ks.tmpl
templates/ce-default-ipxe.tmpl
templates/ce-default-pxelinux.tmpl
templates/ce-net-post-install.sh.tmpl
templates/ce-net_seed.tmpl
templates/ce-root-remote-access.tmpl
templates/ce-update-drp-local.tmpl
tools/test.sh

Just some cleanup based on discussions from Slack:
- Fixed up yaml syntax
- Fixed template syntax to more closely follow style in https://golang.org/pkg/text/template/
- Renamed Params with underscores in them to ones with hyphens

Syntax consistency cleanup (var naming, whitespace, quoted strings)

---

bootenvs/ce-discovery.yml
bootenvs/ce-sledgehammer.yml

Switch back to known good sledgehammer until we can

---

content/templates/net-seed.tmpl

Ensure that security_host/path are configured if local-repo is defined

Allow local-repo to be defined for both Debian/Ubuntu

---

content/params/gohai-inventory.yaml

that the UX could use to avoid allowing edits

added metadata

---

content/stages/sledgehammer-wait.yaml

but not green either.  I picked blue

this is not an in process stage - should not be yellow

---

content/bootenvs/discovery.yml
content/bootenvs/sledgehammer.yml
content/tasks/gohai.yaml

Convert gohai task to use drpcli gohai if present.

Update content to latest sledgehammer!

---

content/bootenvs/centos-7.4.1708.yml
content/bootenvs/centos-7.yml
content/bootenvs/debian-8.yml
content/bootenvs/debian-9.yml
content/bootenvs/discovery.yml
content/bootenvs/sledgehammer.yml
content/bootenvs/ubuntu-16.04.yml
contrib/bootenvs/centos-6.9.yml
contrib/bootenvs/centos-6.yml
contrib/bootenvs/centos-7.3.1611.yml
contrib/bootenvs/scientificlinux-6.8.yml
contrib/bootenvs/ubuntu-14.04.yml

mainly added linux icon to open linux favors and some special icons for sledgehammer.

add icons to bootenvs

---

content/templates/profile.tmpl

Use $() instead of ``

---

content/params/machine-meta.color.yaml
content/params/machine-meta.icon.yaml
content/stages/machine-meta.yaml
content/tasks/machine-meta-setter.yaml
content/templates/machine-meta-setter.sh.tmpl
content/templates/setup.tmpl

Based on the ColorDemo repo, this is helper is generic function for setting metadata.

Meta Data Setting Stage, Task, Params and Template

---

content/templates/part-scheme-default.tmpl

Since the expert_recipe wasn't working anyway, just
let the system choose the atomic format.

Get ubuntu/debian installing again.

---

content/bootenvs/debian-8.yml

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=883938 for more information.

Fix kernel panic issue on Debian 8.10 netboot image

---

README.rst
content/stages/discover-no-gohai.yaml
content/stages/discover.yaml

makes it easier to tell discover for later stages in workflow

change discover color to purple

---

content/params/extra-packages.yaml
content/templates/centos-7.ks.tmpl
content/templates/net-seed.tmpl

file.  To use this feature, you may have to use the install
repos features to get to a fuller set of images.

Allow extra packages to be added into the preseed or kickstart

---

content/bootenvs/centos-7.5.1804.yml
content/stages/centos-7.5.1804.yml

- bump the centos 7.4 to 7.5 version numbers
- missed in the 1708 to 1804 update bump

bump centos-7.4 to centos-7.5

---

content/bootenvs/ubuntu-16.04.yml
content/bootenvs/ubuntu-18.04.yml
content/params/local-repo.yaml
integrations/krib/new-packet-cluster.tf
krib/params/etcd-servers-done.yaml
krib/params/etcd-servers.yaml
krib/params/krib-cluster-masters.yaml
krib/plugins/ha-krib.yaml
krib/profiles/example-krib.yaml
krib/stages/krib-dev-reset.yaml
krib/tasks/krib-config.yaml
krib/tasks/krib-dev-reset.yaml
krib/tasks/kubernetes-install.yaml
krib/templates/etcd-config.sh.tmpl
krib/templates/krib-config.sh.tmpl
krib/templates/krib-dev-reset.sh.tmpl
krib/templates/krib-get-masters.sh.tmpl
krib/workflows/krib-reset-cluster.yaml

Adding docs and echos
Moved cluster reset into it's own stage and workflow

Debugging info and docs

---

content/bootenvs/ubuntu-18.04.yml

- updates `ubuntu-18.04.1-install` to the .1 release
- tested the new bootenv

Update Bionic Beaver to the 18.04.1 ISO

---

content/bootenvs/ubuntu-16.04.yml

pull in July 30 update to 16.04.05

---

krib/stages/krib-helm.yaml
krib/tasks/krib-helm.yaml

forgot to include these small items of docs!

add some docs

---

integrations/rose/new-packet-cluster.tf

terraform plan to bring up ROSE cluster

---

content/params/erase-hard-disk-set.yaml
content/stages/erase-hard-disk-set.yaml
content/tasks/erase-hard-disk-set.yaml

Add erase a subset of disks specified by an optional parameter.

---

krib/params/krib-operate-action.yaml
krib/profiles/krib-operate-cordon.yaml
krib/profiles/krib-operate-delete.yaml
krib/stages/krib-operate-cordon.yaml
krib/stages/krib-operate-delete.yaml
krib/templates/krib-operate.sh.tmpl
krib/workflows/krib-operate-cordon.yaml
krib/workflows/krib-operate-delete.yaml

- adds `delete` and `cordon` Operations to the "operators" patterns
Tested to work.  Can we please get this reviewed and pushed to `tip` ASAP?

adds 'delete' and 'cordon' Operations to KRIB

---

content/._RequiredFeatures.meta
content/templates/change-stage.sh.tmpl
contrib/._RequiredFeatures.meta
krib/._RequiredFeatures.meta
rose/._RequiredFeatures.meta

Also - include deprecation warning for old change stage map template.

Add Required Features metadata to ensure compatibility checks

---

krib/templates/krib-config.sh.tmpl

last pass of the labels code did cover all nodes
In this case, we needed to pull down the admin.conf for the machines.  BUT only keep it for a limited scope!

move label code into place where it works for all nodes

---

krib/._Documentation.meta
krib/params/helm-charts.yaml

Improve cross references.  Add some new features

update docs - see matching provision patch

---

content/bootenvs/discovery.yml
content/bootenvs/sledgehammer.yml
content/templates/setup.tmpl
krib/templates/krib-config.sh.tmpl
krib/templates/krib-helm.sh.tmpl

Also udpate the IP discovery to use an IPv6 address as well.

Changes to support curl with ipv6 addresses.

---

krib/params/krib-cluster-kubernetes-version.yaml

v1.12 is out, we need to pin to that now

update for new release

---

content/._RequiredFeatures.meta
content/bootenvs/centos-7.yml
content/bootenvs/discovery.yml
content/bootenvs/sledgehammer.yml
content/params/kernel-console.yaml
content/params/package-repositories.yaml
content/templates/centos-7.ks.tmpl
content/templates/default-grub.tmpl
content/templates/setup.tmpl

This PR matches https://github.com/digitalrebar/provision/pull/989

Swizzle up discovery and centos-7-install bootenvs to be multiarch aware

---

content/bootenvs/discovery.yml
content/bootenvs/sledgehammer.yml
content/templates/setup.tmpl
krib/params/docker-version.yaml
krib/params/krib-cluster-cni-version.yaml
krib/params/krib-cluster-crictl-version.yaml
krib/stages/krib-live-wait.yaml
krib/templates/docker-install.sh.tmpl
krib/templates/etcd-config.sh.tmpl
krib/templates/krib-dashboard.sh.tmpl
krib/templates/krib-helm-init.sh.tmpl
krib/templates/kubernetes-install.sh.tmpl
krib/templates/mount-disks.sh.tmpl
krib/workflows/krib-reset-cluster.yaml

Update Krib to work with the CoreOS pieces.
Still WIP for testing.

WIP - Update krib and friends to work with CoreOS

---

content/bootenvs/discovery.yml

Allow the join-up.sh script to use IP as a

---

krib/._Documentation.meta

Additional info to make it easier to access the dashboard for k8s beginners

Expanded on accessing the kubernetes dashboard

---

content/params/last-boot-macaddr.yaml

icon for last-boot-mac

---

krib/._Documentation.meta
krib/params/helm-charts.yaml
krib/params/ingress-rook-dashboard-hostname.yaml
krib/params/rook-data-dir-host-path.yaml
krib/profiles/example-k8s-db-ingress.yaml
krib/profiles/example-rook-db-ingress.yaml
krib/profiles/helm-reference.yaml
krib/templates/helm-rook.after.sh.tmpl
krib/templates/helm-rook.before.sh.tmpl
krib/templates/helm-rook.cfg.tmpl
krib/templates/krib-helm.sh.tmpl
krib/templates/krib-ingress-nginx.sh.tmpl
krib/templates/krib-lib.sh.tmpl
krib/templates/krib-longhorn.sh.tmpl

Also added templatebefore and templateafter to krib-helm charts

Updated rook to add ceph dashboard service + ingress and update default path

---

krib/params/helm-charts.yaml
krib/profiles/example-k8s-db-ingress.yaml
krib/profiles/example-rook-db-ingress.yaml
krib/profiles/helm-reference.yaml
krib/templates/krib-helm.sh.tmpl
krib/templates/krib-ingress-nginx.sh.tmpl
krib/templates/krib-lib.sh.tmpl

Fixed bugs with wait_for_ingress
Renamed k8s dashboard ingress

Updates to repos support for helm charts

---

content/workflows/discover-base.yaml

I reversed the color and icon values.

switch color/icon

---

krib/params/kubectl-working-dir.yaml
krib/stages/docker-install.yaml
krib/tasks/docker-install.yaml

pocket is not a valid icon - changing to docker

change pocket to docker icon

---

content/bootenvs/discovery.yml
content/bootenvs/sledgehammer.yml
krib/params/krib-dashboard-enabled.yaml
krib/params/krib-networking-provider.yaml
krib/templates/etcd-config.sh.tmpl
krib/templates/krib-config.sh.tmpl
krib/templates/krib-dashboard.sh.tmpl
krib/templates/krib-helm.sh.tmpl
krib/templates/krib-ingress-nginx.sh.tmpl
sledgehammer-builder/bootenvs/build-sledgehammer.yaml

Fixes line break and whitespace bugs when you define multiple templates

adding line breaks inside ranges so lines don't get run together

---

content/params/gohai-inventory.yaml

updated UX looks for these values more carefully than before.

gohai-inventory should have a schema

---

sledgehammer-builder/._Icon.meta

Live long and prosper with SledgeHANDer

Sledgehammer Buider Icon

---

krib/templates/krib-dev-reset.sh.tmpl

Get profile data from profile and not aggregate through machine.

---

content/templates/setup.tmpl
krib/templates/etcd-config.sh.tmpl
krib/templates/krib-config.sh.tmpl
krib/templates/krib-helm-init.sh.tmpl
krib/templates/krib-lib.sh.tmpl
krib/templates/krib-metallb.sh.tmpl

refs digitalrebar/provision-content/issues/236

added basic support for self healing etcd cluster

---

krib/profiles/example-krib-ha.yaml
krib/tasks/krib-dev-reset.yaml
krib/templates/etcd-config.sh.tmpl
krib/templates/krib-helm-init.sh.tmpl
krib/templates/mount-disks.sh.tmpl

adding function to umount when the /dev/sda1
and adding option -f on mkfs.xfs command

adding function to umount when the /dev/sda1

---

content/stages/centos-setup-repos.yaml
content/templates/centos-drp-only-repos.sh.tmpl

based upon the package-repositories

Add stage that allows the repos to be configured in centos based systems

---

krib/params/docker-version.yaml
krib/params/etcd-version.yaml
krib/params/krib-cluster-cni-version.yaml
krib/params/krib-cluster-crictl-version.yaml
krib/params/krib-cluster-kubernetes-version.yaml

docker 18.09
etcd 3.3.13
cni 0.7.5
crictl 1.14.0
kubernetes 1.14.1

update docker, etcd, cni, crictl, kubernetes

---

coreos/bootenvs/coreos-2135.6.0-disk.yaml
coreos/bootenvs/coreos-2135.6.0-live.yaml
coreos/stages/coreos-install.yaml
coreos/stages/coreos-live.yaml

Updating the CoreOS content to match the latest stable: https://coreos.com/releases/#2135.6.0

Update CoreOS to 2135.6.0

---

krib/templates/krib-rook-ceph.sh.tmpl

Hey guys,
This PR allows the operator to select a specific version of rook-ceph to install (they've been making changes recently which has broken the previous, "stable" version of this task!)
Cheers!
D

Be specific about rook-ceph version

---

validation/templates/validation-lib.tmpl

Adds several checks to the validation lib.
1. check dns name of `Machine.Name` and make sure it points at a given IP
2. ensure a provide IP is in a valid ipv4 format
3. make sure an IP + GW is in the provided NM

Validation lib

---

image-builder/templates/image-builder-stage.sh.tmpl
image-builder/templates/image-capture.sh.tmpl

added missing . to Param for template expansion

fixed param error when installing image-builder

---

flash/params/flash-list.yml
flash/tasks/dell-firmware-flash-list.yml
flash/tasks/flash-discover.yml
flash/tasks/hpe-firmware-flash-list.yml
flash/tasks/lenovo-firmware-flash-list.yml
flash/tasks/lenovo-firmware-flash.yml
flash/templates/prep-usb-nic.sh.tmpl

Split flash-list into per-vendor flash-list style like
basic flash.

Update lenovo-flash-list support

---

validation/templates/validation-lib.tmpl

- adds NIC Count and minimum required "UP" count validation function

add validate_nic_counts to validation libarary

---

content/bootenvs/centos-7.6.1810.yml
content/bootenvs/centos-7.7.1908.yml
content/stages/centos-7.7.1908.yml

- move the 1810 version references to correctly point at 1810 ISO copies
- add 7.7.1908 bootenv
- shift the generic centos-7 to point to the 7.7.1908 version

add centos-7.7.1908, shift c7 to it

---

validation/._Documentation.meta
validation/params/validate-nic-required-up.yaml
validation/params/validation-errors.yaml
validation/params/validation-list-parameter.yaml
validation/params/validation-post-discover.yaml
validation/params/validation-post-hardware.yaml
validation/params/validation-post-install.yaml
validation/stages/validation-post-discover.yaml
validation/stages/validation-post-hardware.yaml
validation/stages/validation-post-install.yaml
validation/tasks/validate-nic-counts.yaml
validation/tasks/validation-start.yaml
validation/tasks/validation-stop.yaml
validation/tasks/validation-test-fail.yaml
validation/tasks/validation-test-fatal.yaml
validation/tasks/validation-test-success.yaml

Enhance the validation content pack documentation.
- Add to the base ._Documentation, with sections on Use, Developing, etc.
- Add to each of the param/task/stages/etc content pieces

Update validation documentation

---

flexiflow/._Documentation.meta
flexiflow/params/flexiflow-maintenance-mode.yaml
flexiflow/stages/flexiflow-workflow.yaml
flexiflow/stages/test-flexiflow-start.yaml
flexiflow/stages/test-flexiflow-stop.yaml
flexiflow/stages/test-flexiflow-workflow.yaml
flexiflow/tasks/flexiflow-workflow.yaml
flexiflow/tasks/test-flexiflow-start.yaml
flexiflow/tasks/test-flexiflow-stop.yaml
flexiflow/workflows/test-flexiflow-workflow-include.yaml
flexiflow/workflows/test-flexiflow-workflow-main.yaml

- adds flexiflow inject workflow capability
- includes test content - to use, run workflow `test-flexiflow-workflow-main`
_Expect heaps of hate leveled at me._

Add flexiflow workflow capability

---

classify/._Documentation.meta
classify/params/classification-data.yaml
classify/params/classify-custom-functions.yaml

WIP-Updated docs to highlight examples better

---

os-other/templates/redhat-subscription-register.sh.tmpl

- fix failed `.ParamExists` attempt

Fix Param to ParamExists

---

content/templates/setup.tmpl
go.mod

Attempt to use drpcli as jq instead by setting links for

---

go.mod
task-library/params/inventory-collect.yaml
task-library/params/inventory-raid-controllers.yaml
task-library/params/inventory-raid-disks.yaml
task-library/params/inventory-raid-total-disks.yaml
validation/params/validate-parameters.yaml
validation/tasks/validate-parameters.yaml

Also add more inventory pieces
Start parameter validation task and parameter

Update to beta7

---

go.sum
validation/params/validate-record-parameters.yaml
validation/stages/validation-record-parameters.yaml
validation/tasks/validate-record-parameters.yaml

build a validation parameters object and store it in
validate/parameters based upon the parameters in the
validate/record-parameters parameter.

Add validation-record-parameters.  This stage will gather and

---

edge-lab/._Documentation.meta
edge-lab/params/edge-lab-reboot-workflow.yaml
edge-lab/stages/edge-lab-bootstrap.yaml
edge-lab/stages/edge-lab-reboot-to-discover.yaml
edge-lab/tasks/edge-lab-bootstrap-isos.yaml
edge-lab/tasks/edge-lab-bootstrap-lock.yaml
edge-lab/tasks/edge-lab-bootstrap-prefs.yaml
edge-lab/tasks/edge-lab-bootstrap-ssh.yaml
edge-lab/tasks/edge-lab-bootstrap-subnet.yaml
edge-lab/tasks/edge-lab-reboot-workflow.yaml
edge-lab/templates/k3s-install.sh.tmpl
edge-lab/workflows/edge-lab-bootstrap.yaml
edge-lab/workflows/edge-lab-reboot-to-discover.yaml

Includes adding lock to end of bootstrap
protect create of subnet for idempotency

Edge Lab add icons for bootstrap

---

edge-lab/._Documentation.meta

fix rst formatting bullets

---

integrations/docker-context/ansible-dockerfile
integrations/docker-context/runner-dockerfile
integrations/docker-context/terraform-dockerfile

this is an advanced pull to position files needed by the bootstrap-context stage.
this location is a central control location for the shared reference dockerfiles.

shared for dockerfiles used by context bootstrapper

---

content/templates/setup.tmpl

Just a comment helper to help people find help on the helper that is sourced in for `setup.tmpl`.

Add helper comment help for people to find source

---

edge-lab/._Documentation.meta

formatting fix - need CR

---

flash/tasks/dell-firmware-flash-list.yml
flash/tasks/hpe-firmware-flash-list.yml
flash/tasks/lenovo-firmware-flash-list.yml

Handle curl failure and error if the file is missing.

---

content/stages/discover-nobootenv.yaml
content/stages/discover.yaml

also adds some docs to discover.yaml

handle case where discovery should not force sledgehammer

---

content/bootenvs/debian-9.yml

update sha of debian 9 bootenv

update debian 9 bootenv

---

edge-lab/params/edge-lab-helm-version.yaml
edge-lab/tasks/edge-lab-helm-charts.yaml
edge-lab/tasks/edge-lab-helm-install.yaml

replaces golang variable with bash variable.
scoping was preventing the logic from working correctly.

bug: change to bash variable from gotemplate variable

---

task-library/params/dr-server-ha-address.yaml
task-library/params/dr-server-ha-id.yaml
task-library/params/dr-server-ha-interface.yaml
task-library/params/dr-server-ha-passive.yaml
task-library/params/dr-server-ha-token.yaml
task-library/params/dr-server-replace-drp.yaml
task-library/params/dr-server-zip-url.yaml
task-library/tasks/dr-server-install.yaml
task-library/templates/dr-server-ha.conf.tmpl

Task installs DRP on a machine with a number of air-gap and dev options
Includes building the HA configuration file.

DRP server install

---

vmware-lib/content/._Documentation.meta
vmware-lib/content/params/govc-command.yaml
vmware-lib/content/params/govc-template-json.yaml
vmware-lib/content/params/govc-username.yaml
vmware-lib/content/params/vcsa-deploy-template-json.yaml
vmware-lib/content/profiles/govc-vcsa-test.yaml
vmware-lib/content/profiles/vcsa-deploy-EXAMPLE.yaml
vmware-lib/content/tasks/govc-command.yaml
vmware-lib/content/workflows/govc-vcenter-create.yaml

- fixes minor RST formatting nits

docs(vmware-lib): Fix RST formatting errors.

---

classify/._Documentation.meta
classify/params/classification-data.yaml
classify/params/classification-disable-classifier.yaml
classify/params/classify-custom-functions.yaml
classify/stages/classify.yaml

- fixes various RST formatting errors

docs(classify): Fix RST formatting errors.

---

classify/._Documentation.meta
classify/params/classify-custom-functions.yaml
classify/stages/classify.yaml
classify/tasks/classify.yaml
classify/workflows/classify.yaml

- clean up RST formatting
- enhance per-object inline documentation
- add examples and enhance top-level doc information

doc(classify): Update classifier docs, examples, etc.

---

image-builder/._Documentation.meta
image-builder/stages/image-builder-start.yaml
image-builder/tasks/image-builder-cleanup.yaml
image-builder/tasks/image-capture.yaml
image-builder/tasks/image-install-cloud-init.yaml
image-builder/tasks/image-reset-package-repos.yaml
image-builder/tasks/image-stage.yaml

doc(image-builder): Update documentation.

---

content/._Documentation.meta
content/params/gohai-inventory.yaml
content/params/hostname.yaml
content/params/kernel-options.yaml
content/params/kexec-ok.yaml
content/params/ntp-servers.yaml
content/params/provisioner-default-password-hash.yaml
content/params/runner-tmpdir.yaml
content/params/sledgehamer-enforce.yaml
content/params/ux-air-gap.yaml

doc(community-content) Updated docs for params

---

content/bootenvs/discovery.yml
content/bootenvs/sledgehammer.yml

Kernel update for RPi discovery & sledgehammer.

feature(content): Update RPi Discovery to 5.4.34

---

content/stages/exit-context.yaml

You could just as easily do this with task construction, but a stage
makes building the workflows a bit easier.

feat(exit-context): Add a stage that just exits a context.

---

content/templates/discovery-common-bootstrap.sh.tmpl
task-library/tasks/bootstrap-contexts.yaml
task-library/workflows/discover-joinup.yaml

this logic change fixes that
this was introduced in tip - no need for release notes
added small fixes:
* to better use new docker pull images.
* to not automatically try to setup the firewall

fix(content): find-by-saved-uuid logic was missing saved uuids

---

edge-lab/params/edge-lab-dashboard-token.yaml
edge-lab/params/edge-lab-helm-download-url.yaml
edge-lab/params/k3s-download-url.yaml
edge-lab/params/openfaas-password.yaml

cosmetic to meta data that enables new UX feature to cut and paste params

style(edge-lab): enable copy and paste from select params

---

task-library/._Documentation.meta
task-library/params/ansible-inventory.yaml
task-library/stages/ansible-inventory.yaml
task-library/stages/bootstrap-advanced.yaml
task-library/stages/inventory.yaml
task-library/tasks/ansible-inventory.yaml

Updated some of the task-lib docs

docs(doc day updates)

---

edge-lab/stages/edge-lab-bootstrap.yaml
edge-lab/tasks/edge-lab-helm-charts.yaml
edge-lab/tasks/edge-lab-helm-install.yaml
edge-lab/templates/k3s-install.sh.tmpl
edge-lab/workflows/k3s-install.yaml

very minor fix - NFS takes time and can cause problems, don't do by default at this time.

refactor(edge-lab): remove NFS mount bootstrap for now, it's not used

---

vmware-lib/._Prerequisites.meta
vmware-lib/._Tags.meta

- add `._Tags.meta` info
- add `._Prerequisites.meta` info

enhance(vmware-lib): Add Tags and Prerequisites

---

dev-library/stages/hello-world.yaml
dev-library/tasks/hello-world.yaml
dev-library/workflows/hello-world.yaml

Simple workflow that runs a small script on the target host as confirmation that workflow is working.
Supports Windows, Linux, and MacOS X.  The target `OS` of `esxi` seems to fail, so has been removed for the moment.
Tested on Windows and Linux.

enhance(dev-library): Add Hello World workflow

---

krib/params/krib-metallb-version.yaml

Upstream changed its main branch name.

krib: fix metallb upstream branch name

---

content/stages/bootstrap-base.yaml

setting prefs is more important, do it first.

refactor(provision-content): reorder to set prefs first

---

content/bootenvs/sledgehammer.yml
content/params/drp-agent.auto-update.yaml
content/params/drp-agent.skip-runnable.yaml
content/stages/drp-agent.yaml
content/tasks/drp-agent-install.yaml
content/tasks/set-machine-ip.yaml
content/templates/drp-agent-cfg.yaml.tmpl
drp-prom-mon/profiles/install-grafana.yml
image-builder/._Documentation.meta
image-builder/workflows/image-builder-centos.yaml
image-builder/workflows/image-builder-rhel.yaml
image-builder/workflows/image-builder-ubuntu-bionic.yaml
integrations/rose/new-packet-cluster.tf
krib/workflows/krib-install-cluster.yaml
os-other/workflows/rhel-server-7-install.yaml
proxmox/content/._Documentation.meta
proxmox/content/workflows/lab-drp-setup.yaml
rose/workflows/rose-install-cluster.yaml
task-library/workflows/centos-7-base.yaml
task-library/workflows/centos-base.yaml
task-library/workflows/fedora-base.yaml
task-library/workflows/ubuntu-base.yaml
validation/stages/validation-post-install.yaml

drpcli agent has been a supported thing for quite awhile, so use it.

Use drp agent for everything

---

packer-builder/content/params/packer-builder-upload-image.yaml
packer-builder/content/stages/packer-builder-upload-to-drp.yaml
packer-builder/content/tasks/packer-builder-build-image.yaml
packer-builder/content/tasks/packer-builder-upload-to-drp.yaml
packer-builder/content/workflows/packer-setup-and-build.yaml
packer-builder/content/workflows/packer-upload-only.yaml

- add upload pieces to the Packer Builder content

WIP enhance(packer-builder): Add upload pieces to Packer Builder

---

dev-library/params/hello-message.yaml
dev-library/tasks/hello-world.yaml

- add `hello/message` to `hello-world` workflow/task
- allows customized message to differentiate different runs

enhance(dev-library): Add hello/message for hello-world

---

content/bootenvs/ubuntu-20.04-install.yml
os-other/params/oscap-configuration.yaml
os-other/params/redhat-rhsm-organization.yaml
vmware-lib/content/._Documentation.meta
vmware-lib/content/params/govc-ova-location.yaml
vmware-lib/content/stages/govc-vsan-claim-disks.yaml
vmware-lib/content/stages/govc-wait-for-ova.yaml

minor RST formatting fixes to:
- drp-community-content
- vmware-lib
- os-other

bug(doc): Minor doc formatting fixes across content packs

---

.gitignore
task-library/workflows/discover-joinup.yaml

clarify something from community discussion

doc(task-library): document discover requirement for join-up

---

packer-builder/README.md
packer-builder/packer/windows-10-1903.json
packer-builder/packer/windows-10-1909-uefi.json
packer-builder/packer/windows-10-1909.json
packer-builder/packer/windows-10.json
packer-builder/packer/windows-2012-r2.json
packer-builder/packer/windows-2016.json
packer-builder/packer/windows-2019-uefi.json
packer-builder/packer/windows-2019.json

- fix VNC definitions for newer QEMU argument processing
- drop the post-processor-check.sh
- add both post-processors where missing

fix(packer-builder): Fix JSON defs for post-processor and VNC

---

edge-lab/tasks/edge-lab-setup-nfs.yaml
task-library/tasks/bootstrap-contexts.yaml
task-library/tasks/terraform-apply.yaml

template IDs should not be duplicated.

refactor(task-lib): minor cleanups for naming and descriptions

---

image-builder/templates/image-builder-cleanup.sh.tmpl
image-builder/workflows/image-builder-centos8.yaml

- add CentOS8 workflow for image builder
- fix cleanup to not try and remove rescue image in C8 - it's not generated now

enhance(image-builder): Add CentOS 8 image build/capture supoport

---

dell-support/params/dell-dsu-base-url.yml
dell-support/params/dell-dsu-block-release.yml
dell-support/params/dell-dsu-mirror-debug.yml
dell-support/params/dell-dsu-mirror-path.yml
dell-support/params/dell-dsu-mirror-releases.yml
dell-support/params/dell-dsu-skip-keys.yml
dell-support/params/dell-dsu-skip-releases.yml
dell-support/stages/dell-dsu-repo-mirror.yml
dell-support/tasks/dell-dsu-repo-mirror.yml
dell-support/tasks/dell-dsu-setup.yml

- fix the URLs paths for explicitly defined DSU Block Releases - they've been moved by Dell
- add Repo Mirror scripts to help create local mirror copies of DSU repo

enhance(dell-support): Add DSU Mirroring tools, Fix Repo URLs

---

flash/._Prerequisites.meta

Adds additional Prerequisites for the Flash content.
drp-community-content is `setup.tmpl`
task-library ... I totally forget why I added that, but it needed it?

enhance(flash): Add additional Prerequisites

---

vmware-lib/content/._Documentation.meta
vmware-lib/content/params/esxi-dvs-mappings.yaml
vmware-lib/content/params/esxi-dvs-memberships.yaml
vmware-lib/content/params/esxi-member-reference.yaml
vmware-lib/content/params/govc-debug.yaml
vmware-lib/content/profiles/cluster.yaml
vmware-lib/content/stages/govc-dvs-create.yaml
vmware-lib/content/stages/govc-vsan-claim-disks.yaml
vmware-lib/content/tasks/esxi-vsan-configure-host.yaml
vmware-lib/content/tasks/govc-cluster-create-fqdn.yaml
vmware-lib/content/tasks/govc-cluster-create-with-vsan-deprecated.yaml
vmware-lib/content/tasks/govc-cluster-create.yaml
vmware-lib/content/tasks/govc-dvs-create.yaml
vmware-lib/content/tasks/govc-vsan-claim-disks.yaml
vmware-lib/content/tasks/govc-vsan-cluster-get.yaml
vmware-lib/content/tasks/govc-vsan-cluster-operations.yaml
vmware-lib/content/tasks/govc-vsan-destroy-cluster.yaml
vmware-lib/content/templates/govc-lib.sh.tmpl
vmware-lib/content/workflows/govc-cluster-create.yaml
vmware-lib/content/workflows/govc-dvs-create.yaml
vmware-lib/content/workflows/govc-vsan-build-and-claim.yaml
vmware-lib/dockerfiles/dockerfile-govc
vmware-lib/dockerfiles/dockerfile-govc-pwsh
vmware-lib/dockerfiles/dockerfile-pwsh
vmware-lib/examples/pyvmomi-connect-test.py
vmware-lib/tools/dockerhub-containers.sh
vmware-lib/tools/drpcli-commands.sh

- various minor tweaks and fixes to VSAN
- minor fixes to cluster-create tools
- adds Distributed Virtual Switches (DVS) (or Virtual Distributed Switches - VDS; depending on who you ask) tooling

enhance(vmware-lib): Add DVS mgmt, fixes to VSAN

---

task-library/tasks/ansible-join-up.yaml
task-library/templates/ansible-playbooks-test-playbook.yaml.tmpl

fighting through some Ansible debugging... so I added some more outputs
issue in the end was changing the default rsa/user for aws and google.

refactor(task-library): add debugging helper to ansible runner

---

image-builder/params/image-builder-additional-excludes.yaml
image-builder/params/image-builder-additional-packages.yaml
image-builder/params/image-builder-additional-tar-options.yaml
image-builder/params/image-builder-skip-package-reset.yaml
image-builder/tasks/image-update-packages.yaml
image-builder/templates/image-capture.sh.tmpl
image-builder/templates/image-reset-package-repos.sh.tmpl
vmware-lib/content/params/ansible-additional-options.yaml
vmware-lib/content/tasks/ansible-vmware-migrate-vmk.yaml
vmware-lib/content/tasks/ansible-vmware-object-rename.yaml
vmware-lib/content/templates/govc-lib.sh.tmpl
vmware-lib/content/workflows/esxi-sddc-cluster-configure.yaml
vmware-lib/content/workflows/esxi-sddc-vcenter-deploy.yaml

- adds Param option to set additional excludes, with default for Grub config pieces
- adds Param for adding additional packages, with default for grub/efi and various software raid components
- adds skip option for reset package respositories task
Tested against CentOS 8.

Imgbldr pkg and file fixes

---

content/stages/empty-gpt-tables.yaml
content/tasks/empty-gpt-tables.yaml

- add a very fast disk wipe process via sgdisk gpt partition table wipe

enhance(drp-community-content): Add empty-gpt-tables stage/task

---

flash/params/flash-list-installed-hash.yml
flash/params/flash-list-installed.yml
flash/tasks/dell-firmware-flash-list.yml
flash/tasks/hpe-firmware-flash-list.yml
flash/tasks/lenovo-firmware-flash-list.yml
flash/templates/flash-list-installed.sh.tmpl

This is in case the profile gets removed from the system.

feat(flash): record list of installed packages and a hash

---

cloud-wrappers/params/aws-access-key.yaml
cloud-wrappers/params/aws-ami-id.yaml
cloud-wrappers/params/aws-instance-type.yaml
cloud-wrappers/params/aws-region.yaml
cloud-wrappers/params/aws-secret-key.yaml
cloud-wrappers/params/aws-security-groups.yaml
cloud-wrappers/params/azure-appId.yaml
cloud-wrappers/params/azure-image.yaml
cloud-wrappers/params/azure-password.yaml
cloud-wrappers/params/azure-region.yaml
cloud-wrappers/params/azure-size.yaml
cloud-wrappers/params/azure-subscription_id.yaml
cloud-wrappers/params/azure-tenant.yaml
cloud-wrappers/params/cloud-provider.yaml
cloud-wrappers/params/google-boot-disk-image.yaml
cloud-wrappers/params/google-credential.yaml
cloud-wrappers/params/google-instance-type.yaml
cloud-wrappers/params/google-project-id.yaml
cloud-wrappers/params/google-region.yaml
cloud-wrappers/params/google-zone.yaml
cloud-wrappers/params/linode-instance-image.yaml
cloud-wrappers/params/linode-instance-type.yaml
cloud-wrappers/params/linode-region.yaml
cloud-wrappers/params/linode-root-password.yaml
cloud-wrappers/params/linode-token.yaml
cloud-wrappers/tasks/cloud-inspect.yaml
cloud-wrappers/tasks/cloud-validate.yaml
cloud-wrappers/templates/cloud-provision-reference.tf.tmpl

Adds Azure VM create to cloud-wrapper.
Tested w/ all 4 clouds.

feat(cloud-wrapper): add azure cloud support

---

content/bootenvs/ubuntu-18.04.yml

Updated Ubuntu 18.04 to the 18.04.5 release

feat(community-content): updated Ubuntu 18.04

---

task-library/params/dr-server-initial-password.yaml
task-library/params/dr-server-initial-user.yaml
task-library/tasks/ansible-join-up.yaml
task-library/tasks/dr-server-install.yaml

Simplify the install process:
refactor(task-library): remove endpoint register from dr-server-install
fix(task-library): remove unneeded extra claims
fix(task-library): add new required params
Small included item:
refactor(task-library): stop setting colors in tasks as side-effects

feat(task-library): include user/password setting in dr-server install

---

task-library/params/inventory-collect.yaml
task-library/params/inventory-tpm-device.yaml
task-library/params/inventory-tpm-fail-on-notools.yaml
task-library/params/inventory-tpm-public-key.yaml
task-library/tasks/inventory.yaml
task-library/templates/tpm-info.sh.tmpl

This will attempt to record the public key from the TPM.
If not present or tools not available, those will be in the
inventory variable.  It will store the base64 encoding of the
public key.

feat(content): add TPM public key recorder for inventory.

---

dev-library/stages/reboot-event.yaml
dev-library/tasks/reboot-event.yaml
dev-library/workflows/reboot-event.yaml
edge-lab/params/edge-lab-reboot-workflow.yaml
edge-lab/tasks/edge-lab-reboot-workflow.yaml
task-library/tasks/ansible-join-up.yaml

very handy for UX testing this special event, this workflow will send a powercycle event
for style, I also added it to the ansible-join.up and edge-lab soft reboot tasks.

feat(dev-library): send powercycle event for UX testing

---

cloud-wrappers/templates/cloud-provision-reference.tf.tmpl
task-library/tasks/bootstrap-contexts.yaml

Adds newly required incantations for Terraform providers when using v0.14+
Tested on all 4 providers.

fix(cloud-wrap): fix terraform 0.14 requirements

---

content/templates/setup.tmpl
edge-lab/._Documentation.meta
edge-lab/tasks/edge-lab-reboot-workflow.yaml
kube-lib/._Documentation.meta
task-library/tasks/terraform-apply.yaml

included some other minor tuning items:
1) docs for kube-lib
2) sleep in reset cycle
3) reduce log output in terraform apply

fix(contents): handle /home/rob not set case

---

content/bootenvs/discovery.yml
content/bootenvs/sledgehammer.yml
content/profiles/sledgehammer-centos8-v4.6.0.yaml
sledgehammer-builder/tasks/sledgehammer-create-image.yaml

fix(sledgehammer-builder): Support UEFI better.

fix(content): Update sl8 for new cdboot.iso

---

cloud-wrappers/params/cloud-provider.yaml
cloud-wrappers/params/digitalocean-image.yaml
cloud-wrappers/params/digitalocean-region.yaml
cloud-wrappers/params/digitalocean-size.yaml
cloud-wrappers/params/digitalocean-token.yaml
cloud-wrappers/tasks/cloud-validate.yaml
cloud-wrappers/templates/cloud-provision-reference.tf.tmpl
task-library/params/network-firewall-ports.yaml
task-library/tasks/network-firewall.yaml

Extend the cloud-wrapper list to include digital ocean.

feat(cloud-wrapper): add digitalocean support

---

content/bootenvs/discovery.yml
content/templates/esxi-join-up.py.tmpl

Adds the esxi-join-up.py script to the discovery bootenv

feat(content): added esxi-join-up script

---

content/bootenvs/ubuntu-16.04.yml
content/bootenvs/ubuntu-18.04-arm64-hwe.yml
content/bootenvs/ubuntu-18.04.yml
content/bootenvs/ubuntu-20.04-install.yml

Provides link to helpful KB article related to the note.

doc(community-content): add link to KB article in note

---

vmware-lib/content/tasks/ovftool-deploy.yaml

Fixes and enhancements:
- minor typo fixes
- add safety check and appropriate error message around missing `govc/datastore` value
- ovftool command failure hints around OVFtools wrongly documented boolean True/False handling

enhance(vmware-lib): Enhance safety checks and error output for OVFtool deployments

---

content/bootenvs/discovery.yml
content/templates/esxi-join-up.py.tmpl

Added ability to esxi-join-up to utilize the signed vib

fix(esxi-join-up): support with signed vib

---

os-other/templates/rhel-8.ks.tmpl

Remove the hard coded BaseOS and AppStream references; Add appropriate `InstallRepos` support.

enhance(os-other): Add InstallRepos to RHEL 8 kickstart

---

content/bootenvs/discovery.yml

Adjusted docs for the esxi-joinup script

doc(discovery): adjusted doc for esxi-joinup

---

task-library/tasks/dr-server-install.yaml

correct assumption that install.sh installs JQ

fix(task-library): jq not installed by install.sh

---

task-library/params/ansible-playbooks.yaml
task-library/tasks/ansible-playbooks-local.yaml

request from community
docs are longer than the code :)

feat(task-library): ansible local has optional template expansion in extra-vars

---

cloud-wrappers/contexts/ansible.yaml
cloud-wrappers/contexts/terraform.yaml

enabling download from UX requires HTTPS and CORS

refactor(cloud-wrapper): use https path with CORS

---

image-builder/tasks/image-install-cloud-init.yaml

Added crazy hack using ssh to finally trick ubuntu into installing cloud-init

fix(image-builder): fixed issue for ubuntu 18

---

content/stages/bootstrap-base.yaml

ensures that gohai data is available on self-runner machine.

refactor(content): include gohai stage in bootstrap for self-runner

---

edge-lab/params/edge-lab-gpio.yaml
edge-lab/stages/edge-lab-reboot-to-discover.yaml
edge-lab/tasks/edge-lab-gpio.yaml
edge-lab/tasks/edge-lab-reboot-workflow.yaml

This allows users to easily turn on/off LEDs attached to the RPis.
Also, fixed bugs in the reboot workflow that was keep it from being settable.

feat(edge-lab): automate GPIO pin settings for SQUID

---

image-builder/._Documentation.meta
image-builder/workflows/image-builder-rhel8.yaml

-  Adds RHEL 8 image builder workflow.  
-  Minor cleanup and tweaks to docs

enhance(image-builder): Add RHEL 8 Image Build workflow, doc tweaks

---

content/params/package-repositories.yaml
content/tasks/enforce-sledgehammer.yaml

fix(content): Update sledgehammer to be centos-7 or centos-8 correctly

fix(content): update package-repositories for centos-8.3

---

content/params/network-data-parser-debug.yaml
edge-lab/._Documentation.meta
krib/._Documentation.meta
kube-lib/._Documentation.meta
task-library/params/storage-mount-devices.yaml
task-library/tasks/storage-mount-devices.yaml
vmware-lib/content/params/esxi-datastore-mappings.yaml

Fixes many formatting and cross reference errors in documentation.

fix(doc): Various content doc fixes

---

proxmox/content/tasks/kvm-enable-nested.yaml
proxmox/content/tasks/proxmox-debconf-set-selections.yaml
proxmox/content/tasks/proxmox-lab-accounts.yaml
proxmox/content/tasks/proxmox-lab-createnodes.yaml
proxmox/content/tasks/proxmox-lab-destroy-all-vms.yaml
proxmox/content/tasks/proxmox-lab-destroy-networks.yaml
proxmox/content/tasks/proxmox-lab-destroy-users.yaml
proxmox/content/tasks/proxmox-lab-drp-network.yaml
proxmox/content/tasks/proxmox-lab-network.yaml

Fix the debconf set selections broken template reference.
Cleanup all other Task/Templates to use consistent Name/Contents formatting.

fix(proxmox): Fix debconf selections template references

---

dev-library/tasks/hello-world.yaml

adds ESXi OS to the Meta OS field for the hello-world task

enhance(dev-library): Add ESXi to hello-world task

---

content/bootenvs/discovery.yml
content/templates/esxi-join-up.py.tmpl

Updates the instructions and code to support the vfat migration of the drpy config

fix(esxi-join): updates the esxi join for vfat

---

cloud-wrappers/contexts/ansible.yaml
cloud-wrappers/contexts/terraform.yaml
integrations/docker-context/ansible-dockerfile
integrations/docker-context/runner-dockerfile
integrations/docker-context/terraform-dockerfile
task-library/tasks/ansible-join-up.yaml

Also updates the DRPCLI to v4.6 in the context containers.

feat(task-lib): add keys from access-keys when joining

---

tools/cloud-profiles.sh

Expands the cloud-wrapper helper script to also setup managed endpoints
This makes it easy to setup cloud based instances from the manager.
This is a short term approach for trial users.
It is NOT a substitute for using multi-site manager to control content packs.

feat(cloud-wrapper): expand script to setup remote endpoints too

---

flash/params/flash-lenovo-xcc-reboot-wait.yml
flash/tasks/lenovo-firmware-flash-list.yml
lenovo-support/params/lenovo-onecli-url.yaml

Lenovo hasn't publish a functional onecli that works.
This requires that change.

WIP feat(flash): update to onecli v310+ - still not complete

---

cloud-wrappers/params/mist-api-token.yaml
cloud-wrappers/stages/cloud-decommission.yaml
cloud-wrappers/stages/cloud-inspect.yaml
cloud-wrappers/stages/cloud-site-create.yaml
cloud-wrappers/stages/cloud-site-destroy.yaml
cloud-wrappers/tasks/mist-io-sync.yaml
tools/cloud-profiles.sh

If user has MIST.io, this will synrchronize clouds created w/ CloudWrapper with Mist.io
Handy as a way to monitor and check against orphan VMs
Will No-Op if missing.

feat(cloud-wrapper): mist.io synchronization calls

---

validation/params/validate-failure-mode.yaml
validation/tasks/validate-parameters.yaml
validation/tasks/validation-stop.yaml

Enhances the task `validation-parameters` to be configurable with hard exit or ignore errors.
Clean up golang template generation with so many blank lines.
Enhance `validation-stop` accounting to support the errors fatal or errors ignore conditions.

enhance(validation): Make validation-errors exit configurable

---

flash/params/flash-list.yml
flash/tasks/flash-discover.yml
flash/tasks/generic-flash-list.yml
flash/templates/flash-list-generic.sh.tmpl

This refactors out the common parts of the main loops of the
vendor-specific flash list code, and enhances the flash-list param
to allow for per-flash scripting.

WIP feat(flash): Generic flash support.
