digitalrebar/provision-content

bootenvs/ce-debian-8.yml, bootenvs/ce-debian-9.yml, templates/ce-net-post-install.sh.tmpl, templates/ce-net-seed.tmpl
- Adds Debian Jessie/Stretch boot environments
- Adds params for further configuring the default user
- Sets kernel parameters for installed Ubuntu/Debian on complete
- Stores a copy of the generated preseed at `/var/log/provision.seed`
- Correctly specifies Debian/Ubuntu packaging endpoints
This is sort of a big change - let me know if I should make any changes or remove anything in particular.
=> Debian Support

bootenvs/ce-debian-8.yml, bootenvs/ce-debian-9.yml, bootenvs/ce-ubuntu-16.04.yml, templates/ce-net-post-install.sh.tmpl, templates/ce-net-seed.tmpl, templates/part-scheme-ce-default.tmpl
This introduces a `part-scheme` Param for Debian/Ubuntu boot environments and creates a default `ce-default` `part-scheme`. It also removes a test for Debian Wheezy since we don't have a boot environment for Wheezy.
I have these changes based on #31, so you should look at the latest commit for the subset of actual changes.
This PR also depends on tip at the moment since it uses the `CallTemplate` function
=>  Allow partitioning schemes to be easily configurable

content/params/package-repositories.yaml
This adds a new parameter named package-repositories that will be used to define package repositories thhat systems should use both for OS installation and general purpose package management.
=> Add package-repositories param

content/bootenvs/discovery.yml
If getent hosts fails due to not getting a fixed_ip back, it will
return the host information for the localhost network, resulting in a
system getting "localhost" as a hostname in DRP.  Needless to say,
this is a Bad Idea, so prevent it from happening.
=> Make sure our hostname does not get set to localhost.

content/stages/discover-no-gohai.yaml
handle cases where gohai is failing.
=> Temporarily add a discover stage without gohai to

content/templates/net-seed.tmpl, content/templates/part-scheme-default.tmpl
Please observe that I have not tested this exact change since I've done some more customisation in the seed I run myself, but these config changes should resolve an issue with custom partitioning schemes not being implemented.
`d-i partman/auto expert_recipe string` is incorrect syntax which (my guess, not preseed expert) cause partman to fall back on default atomic scheme.
Using correct syntax cause another problem; Installer can't find a valid root partition if you opt for custom partitions, as there isn't one defined yet. Move the following options:
```
d-i partman/confirm_write_new_label boolean true
d-i partman/choose_partition select finish
d-i partman/confirm boolean true
d-i partman/confirm_nooverwrite boolean true
```
To execute after part scheme.
=> Correct incorrect partman syntax and sequence partman options

content/bootenvs/ubuntu-16.04.yml
- switched from kernel.org to princeton Ubuntu mirror
- kernel.org was taking 15 minutes ... princeton mirror took 10 seconds
- moved from 16.04.3 to 16.04.4 version
=> Switched from Kernel.org to Princeton mirror; moved to 16.04.4

content/stages/complete-nowait.yaml, content/stages/finish-install.yaml, content/stages/machine-meta.yaml, content/stages/prep-install.yaml
These changes are associated with the provision #760 PR.  The runner is longer running, but can still be controlled with change-stage/map options.  In general, these are not needed for standard workflows and the content is updated to reflect that. 
The content should continue to function with pre-#760 PR DRP.
=> Content tweaks to reflect the drpcli runner changes.

content/bootenvs/centos-7.4.1708.yml, content/bootenvs/centos-7.yml
- switch the kernel.org mirror for princeton.edu
- kernel.org is taking around 19 minutes to download
- princeton.edu mirror is taking 12 seconds 
Note: Princeton mirrors have been long term stable mirrors.
=> Switch CentOS 7 mirrors

content/params/rs-debug-enable.yaml, content/templates/setup.tmpl
- enables disabling ``RS_TOKEN`` and ``RS_ENDPOINT`` if desired via shell variable
- add option ``RS_DEBUG_ENABLE`` which allows adding 'set -x' via Param ``rs-debug-enable``
- move sane-exit-codes to use ``RS_`` prefixes - all globals should be prefixed ``RS_``
- support old sane-exit-code shell variables for now (eg ``SUCCESS_CODE``)
- if RS_TOKEN is unset - correctly handle that condition for ``sane-exit-codes``
- add Param of ``rs-debug-enable``, but set it to default false 
NOTE: this is not fully tested - because I'm having issues with ``drpcli contents  unbundle``.   Can't explode CC, modify, reload, and test. 
```
[root@pkt cc]# ../../drpcli contents show drp-community-content > ../cc.json
[root@pkt cc]# ../../drpcli contents show drp-community-content --format=yaml > ../cc.yaml …
```
=> Updates to setup.tmpl, add Param rs-debug-enable

content/bootenvs/ubuntu-18.04.yml, content/stages/ubuntu-18.04.yml
- adds Ubuntu 18.04 (Bionic Beaver) daily ISO builds
- WARNING:  this is a Beta release of Bionic Beaver
- when Ubuntu 18.04 officially releases, a new BootEnv/Stage will be released
=> add BETA Bionic Beaver (daily builds)

content/stages/reorder-uefi-bootorder.yaml, content/tasks/fix-uefi-boot-order.yaml
Sadly, this task can fail on ubuntu 16.04 due to them shipping a buggy
version of efibootmgr and libefivar.
=> Add a stage and task to reorder the boot order during UEFI OS installs.

content/templates/centos-7.ks.tmpl, content/templates/net-seed.tmpl
This gets rid of all manual repo handling in the preseed (for Debian
and Ubuntu) and the kickstart (for Centos, RHEL, etc).  It replaces it
with the repo-handling helpers that dr-provision has provided based on
the package-repositories parameter.
In particular, this PR removes the meaning the "local-repo" param used
to have for Debian/Ubuntu installs, since what it was trying to do can
easily be accomplished by setting up package-repositories to point to
the mirror of your choice for any OS install repos.
=> Zap manual repo handling in the preseed and kickstart.

content/params/gohai-skip.yaml, content/stages/discover-no-gohai.yaml, content/tasks/gohai.yaml
Replaces the need for discover-no-gohai in a more DRP native way using a parameter
Includes deprecation warnings for discover-no-gohai
Also, updates docs for models
=> Use parameter to skip gohai

content/bootenvs/discovery.yml, content/bootenvs/sledgehammer.yml
This makes the discovery and sledgehammer bootenvs use the latest
version of Sledgehammer.  THe new release includes support for
mounting NFS shares.
=> Bump Sledgehammer version.

krib/params/etcd-version.yaml, krib/templates/krib-settings.sh.tmpl
After getting the cert plugin up and running I have found issues etcd version and that the kubeadm after kubernetes 1.11 uses coredns instead of kube-dns.
These fixes are related to #101
=> krib-ha updates for kubernetes 1.11

krib/tasks/krib-dev-reset.yaml
This is a hack for developers to use the dev-reset stage without needed external certificate actions
if password is not default, uses the unsafe/rs-password adhoc param.
=> use rocketskates auth to reset cert in dev reset

krib/params/helm-charts.yaml, krib/params/helm-version.yaml, krib/stages/krib-helm.yaml, krib/tasks/krib-dev-reset.yaml, krib/tasks/krib-helm.yaml, krib/templates/krib-helm-init.sh.tmpl, krib/templates/krib-helm.cfg.tmpl, krib/templates/krib-helm.sh.tmpl, krib/workflows/krib-install-cluster.yaml, krib/workflows/krib-live-cluster.yaml
This pull adds a helm stage that will install helm and tiller (a service role is also added)
And then install any requested charts from helm/charts array
The helm init is idempotent (it checks if tiller is running) and can be run multiple times.
=> Add helm and tiller to KRIB workflows

krib/params/sonobuoy-binary.yaml, krib/params/sonobuoy-wait-mins.yaml, krib/stages/krib-sonobuoy.yaml, krib/tasks/krib-sonobuoy.yaml, krib/templates/krib-sonobuoy.sh.tmpl
Add stage to run Sonobuoy conformance tests on installed cluster.
By default, starts run and does not wait for result.
Stage is idempotent so it can be run latter to collect results.
At this time, relies on the unsafe/rs-password to upload result files to DRP files
THIS IS NOT INCLUDED IN THE DEFAULT WORKFLOW!
=> Add Sonobuoy Stage

content/bootenvs/centos-7.5.1804.yml, content/bootenvs/centos-7.yml, content/bootenvs/debian-8.yml, content/bootenvs/debian-9.yml, content/bootenvs/sledgehammer.yml, content/bootenvs/ubuntu-16.04.yml, content/bootenvs/ubuntu-18.04.yml, content/params/kexec-ok.yaml, content/params/last-boot-macaddr.yaml, content/templates/kexec.tmpl, contrib/bootenvs/centos-6.9.yml, contrib/bootenvs/centos-6.yml, contrib/bootenvs/ubuntu-14.04.yml
This adds support to Sledgehammer and the OS install bootenvs to
allow the Agent to kexec into them instead of rebooting into them.
=> Add oppourtunistic kexec support to bootenvs that should have it.

krib/params/krib-labels.yaml, krib/templates/krib-config.sh.tmpl
Allows users to create ad hoc labels (per profile or node) for Clusters.
default is builder: krib
=> pull node labels from krib/labels param

krib/params/helm-charts-advanced.yaml, krib/params/helm-charts.yaml, krib/params/helm-directives.yaml, krib/profiles/krib-istio-reference.yaml, krib/templates/krib-helm-init.sh.tmpl, krib/templates/krib-helm.sh.tmpl, krib/templates/krib-kubeadm.cfg.tmpl
This update creates advanced options for helm install that include pre and post actions, namespace and names.  This is parallel to the basic charts and is much better than the very simple helm/charts array.
The example includes an istio install chart.
TODO: charts should wait to make sure they are running before moving to the next.
Also fixes config bug.
=> Helm Install with Advanced Directives

content/templates/setup.tmpl
* create new `fixup_path()` function for generic reuse
* move `/usr/local/bin` check to use function
* add `/sbin` and `/usr/sbin` to PATH ... because ... CentOS ...
=> add fixup_path() function, add /sbin and /usr/sbin

krib/params/helm-charts.yaml, krib/params/rook-data-dir-host-path.yaml, krib/profiles/helm-reference.yaml, krib/templates/helm-rook.cfg.tmpl, krib/templates/krib-helm.sh.tmpl
The Rook install needs a Helm Chart AND a kubectl from a template.  These small addition allows rendering templates BEFORE running Helm.  These templates can then be used by helm or kubectl.
In the Rook example, we use the rook operator chart and then build the cluster.yaml needed by rook.  The rook yaml REQUIRES an injected parameter.
This pattern is very powerful for testing advanced helm charts where we want to inject parameters.
Ultimately, we'll want a rook stage.  This improves helm while we are iterating.
=> Update Helm Stage with features that enable Rook install

content/templates/setup.tmpl
- fixes the broken fixup_path()
- used FOO var for testing, didn't revert back to PATH before pushing
- `:sad panda face:`
=> Fixup the fixup_path()

content/bootenvs/discovery.yml, content/bootenvs/sledgehammer.yml
This will cause sledgehammer to wait X seconds if present
after starting the link to wait for port delay switches.
=> Add provisioner.portdelay=X as an option in kernel-console.

content/params/start-over.yaml, content/templates/reset-workflow.tmpl
on startup.  If start-over is set to false, leave the task list alone.
Otherwise, operate as normal.  This will also work for all bootenvs
that use reset-workflow template.
The start-over flag is removed from the machine if directly set upon it.
This allows for a one time effect.
=> Allow sledgehammer to not always reset the workflow/tasks index

content/stages/gce-discover.yaml, content/tasks/gce-discover.yaml
Use the GCE metadata API to get special data about the instances.  Map to existing params.
GCE has more limited data than AWS.  I used the AWS vars because AWS.
=> add google discovery stage

content/bootenvs/discovery.yml
My first pass did not use the DRPCLI to confirm if the machine already existed and relied on the /etc/rs_uuid file.  This is not as reliable as actually checking on machine in the API (thanks @galthaus )
This pull fixes that and adds some docs for join-up users.
The rs_uuid file is maintained/created as a backup.  Most of the diff is from indents.
Tested on GCE and works.
=> tweak join-up script to check for existing from name 

content/bootenvs/discovery.yml, content/bootenvs/sledgehammer.yml, content/params/package-repositories.yaml, content/stages/centos-7.6.1810.yml
1. Fixes centos 7.5 to 7.6.  There were some oversights
in the previous PR.
2. Updates sledgehammer to centos 7.6 for amd64.  Arm rebuild will be
required.
3. Sledgehammer now has two new kernel variables that can
be used to alter start.
The two vars are:
provisioner.postportdelay
which causes a wait in seconds after the link has been brought
up, but hasn't started DHCP.  Defaults to unset.
provisioner.wgetretrycount
which is the number of times to retry the stage2 wget before
dropping to ash.  The default is 10.
=> Sledgehammer update for Centos 7.6 and new kernel params

krib/templates/krib-dashboard.sh.tmpl
Unsecured readonly port 10255 was deprecated and turned off in k8s 1.12.0 kubelet config.
This results in no graphs in the dashboard.
This workaround allows heapster to talk to the secure API until the dashboard gets upgraded to not use heapster.
=> Fixed heapster unable to talk to API

krib/templates/krib-config.sh.tmpl, krib/templates/krib-helm-init.sh.tmpl, krib/templates/krib-keepalived.sh.tmpl
* use master label to taint or untaint masters with `node-role.kubernetes.io/master=:NoSchedule`
* more reliable helm init (enables re-play of the task)
* remove debug output krib-keepalived script template
=> improve master taint, helm init, remove debug

krib/params/helm-charts.yaml, krib/profiles/helm-reference.yaml, krib/stages/krib-helm-charts.yaml, krib/stages/krib-helm-init.yaml, krib/tasks/krib-helm-charts.yaml, krib/tasks/krib-helm-init.yaml, krib/templates/etcd-config.sh.tmpl, krib/templates/krib-config.sh.tmpl, krib/templates/krib-contrail.sh.tmpl, krib/templates/krib-dashboard.sh.tmpl, krib/templates/krib-dev-reset.sh.tmpl, krib/templates/krib-get-masters.sh.tmpl, krib/templates/krib-haproxy.sh.tmpl, krib/templates/krib-helm-init.sh.tmpl, krib/templates/krib-helm.sh.tmpl, krib/templates/krib-ingress-nginx.sh.tmpl, krib/templates/krib-keepalived.sh.tmpl, krib/templates/krib-lib.sh.tmpl, krib/templates/krib-longhorn.sh.tmpl, krib/templates/krib-metallb.sh.tmpl, krib/templates/krib-settings.sh.tmpl, krib/templates/krib-sonobuoy.sh.tmpl
chart templatebefores and templateafters can now be run if the chart is already installed. (This is needed when adding nodes to a cluster that need required packages or configuration to support pods that could be scheduled to them).
replaced exit 1 with xiterr 1.
go template formatting tweaks.
switched to better tiller check method.
added split helm-init and helm-charts tasks and stages.
=> adding more flexibility for templatebefore and templateafer

krib/params/etcd-ip.yaml, krib/params/krib-ip.yaml, krib/params/provider-flannel-config.yaml, krib/templates/etcd-config.sh.tmpl, krib/templates/krib-config.sh.tmpl, krib/templates/krib-get-masters.sh.tmpl, krib/templates/krib-kubeadm.cfg.tmpl, krib/templates/krib-lib.sh.tmpl
This adds `krib/ip` and `etcd/ip` which, if set, are used instead of `Machine.Address` when building the `etcd` and `krib` clusters. These do not have to be the same as each other, either.
This means a KRIB cluster can be told to run over specific network(s) rather than using the network which the node was discovered over by `provision`.
=> KRIB IP Override

content/bootenvs/ubuntu-16.04.yml
Updates Ubuntu Xenial 16.04 Bootenv to latest 16.04.6 version.
NOTE:  As of Feb 28 2019 not all repo mirrors have replicated the package files for this version.  Early access users may need to obtain the ISO image (eg `drpcli bootenvs uploadiso ubuntu-16.04-install`) for installation against the local exploded ISO contents - instead of default installation behavior against hosted repo mirrors.
=> Ubuntu Xenial 16.04.6 updated bootenv

content/stages/aws-discover.yaml, content/stages/centos-7.6.1810.yml, content/stages/centos-7.yml, content/stages/complete-nowait.yaml, content/stages/complete.yml, content/stages/debian-8.yml, content/stages/debian-9.yml, content/stages/discover-no-gohai.yaml, content/stages/discover.yaml, content/stages/erase-hard-disk-set.yaml, content/stages/finish-install.yaml, content/stages/gce-discover.yaml, content/stages/machine-meta.yaml, content/stages/prep-install.yaml, content/stages/reorder-uefi-bootorder.yaml, content/stages/sledgehammer-wait.yaml, content/stages/ssh-access.yaml, content/stages/ubuntu-16.04.yml, content/stages/ubuntu-18.04-arm64-hwe.yml, content/stages/ubuntu-18.04.yml
`RunnerWait` is deprecated and no longer observed.  Removing from all community content stages so as to avoid any confusion.
=> remove deprecated RunnerWait from Stages

krib/templates/krib-config.sh.tmpl
When installing Kubernetes on CoreOS it fails due to missing `/etc/fstab`. Problem described in issue #223.
=> check if /etc/fstab exists before remove swap entry from it

krib/templates/krib-config.sh.tmpl
When installing Kubernetes on CoreOS live bootenv the kernel module br_netfilter isn't loaded. This solves the problem described in issue #224.
=> load kernel module br_netfilter if already not loaded

krib/templates/krib-kubeadm.cfg.tmpl
Api server, scheduler and control manager can't start due to extra volume mount to missing `hyperkube` binary. This PR removes these extra volumes and solves problem described in detail in issue #225.
=> remove extra volumes mount of hyperkube

content/bootenvs/centos-7.6.1810.yml, content/bootenvs/centos-7.yml, content/bootenvs/debian-8.yml, content/bootenvs/debian-9.yml, content/bootenvs/discovery.yml, content/bootenvs/sledgehammer.yml, content/bootenvs/ubuntu-16.04.yml, content/bootenvs/ubuntu-18.04-arm64-hwe.yml, content/bootenvs/ubuntu-18.04.yml
- missing `kernel-options` in sledgehammer bootenv
- added `OptionalParams` references for `kernel-options`
=> add missing kernel-options and OptionalParams

content/params/sledgehamer-enforce.yaml, content/params/sledgehamer-reboot-if-not-in-sledgehammer.yaml, content/stages/discover.yaml, content/stages/enforce-sledgehammer.yaml, content/tasks/enforce-sledgehammer.yaml
Add a task and stage and parameters that can be used to
enforce that a system is sledgehammer.  While hard to do,
there are times that the system can get out of sync with
itself and the admin wants to enforce that the system is
in sledgehammer.  The primary way this happens is that a
Next-Boot-Pxe call failed and the system ended up back
in the original local booted operating system.
The default discovery stage will allow for enforcing this
or a new stage can be added to an existing workflow,
enforce-sledgehammer.
Whether the new task should enforce or not is controlled
by the parameter 'sledgehamer/enforce'.  This defaults to
false, but when set to true, the task will fail if not
in sledgehammer.  Additionally, the parameter,
'sledgehammer/reboot-if-not-in-sledgehammer`, when set
to true …
=> Add a task and stage and parameters that can be used to

sledgehammer-builder/tasks/sledgehammer-stage-bits.yaml
- adds sipcalc 1.1.6-15 from Fedora Core 30 build packages
- staged on rackn S3 bucket for retrieval
- original source location: https://koji.fedoraproject.org/koji/packageinfo?packageID=8762
- tested successfully for x86_64 build sledgehammer
- `aarch64`, `armv7hl`, and `i686` packages exist, but those builds have not been tested
* relies on `uname -p` to return a match to above values
* if ARM versions don't match, some `case` mangling may need to be added to get the right package version
=> add sipcalc to sledgehammer

content/params/dns-search-domains.yaml, content/params/dns-servers.yaml
- add params `dns-servers` and `dns-search-domains`
- currently only used in the ESXi content
- useful for all bootenv content types
=> add dns search domains and servers

content/params/hostname.yaml
Allow setting a hostname.  In some use cases, the DHCP provided
provisioning name (the templatized `.Machine.Name`) may not be
correct for final production personality of the Machine.
This value could be set as a Param/Profile on the machine either
by a human operator, or subsequent integration with IPAM, SoR, or
other services.
This is used in the VMware ESXi provisioning kickstarts.
=> add hostname param

krib/templates/etcd-config.sh.tmpl
fix malformed URL while downloading
=> use -o since -O is used to set remote name as file name

krib/templates/docker-install.sh.tmpl
Seems like docker packages on C7 at least are not creating `/etc/docker` on install anymore - so the creation of `/etc/docker/daemon.json` if specifying `docker/daemon` fails as the directory doesn't exist.
=> Make sure docker config dir exists before trying to create daemon.json

content/bootenvs/sledgehammer.yml, content/params/detected-bios-mode.yaml
Every time a system boots into Sledgehammer for whatever reason, the
system will now recored what mode the system firmware appears to be
operating in.
=> Add a Param that tracks the most recently detected boot mode.

content/params/runner-tmpdir.yaml
This lets the location that the runner will use to store the
scratch files it uses in the case that we cannot rely on the continual
availability of the system default location.
=> Add a runner-tmpdir param.

krib/params/etcd-cluster-client-vip-port.yaml, krib/tasks/etcd-config.yaml, krib/templates/etcd-config.sh.tmpl, krib/templates/krib-haproxy.cfg.tmpl, krib/templates/krib-kubeadm.cfg.tmpl
Hey guys,
Here's a small PR to make the etcd cluster as "HA" as the api server. The PR introduces a new optional param `etcd/cluster-client-vip-port` (default 8379), and configures an haproxy frontend/backend to serve etcd on this port. `kubeadm.cfg` is updated to use this HA etcd endpoint, rather than individual etcd servers.
Cheers!
D
=> Make etcd ha

krib/params/etcd-cluster-client-vip-port.yaml, krib/params/krib-cluster-i-am-master.yaml, krib/params/krib-cluster-selective-mastership.yaml, krib/tasks/etcd-config.yaml, krib/templates/etcd-config.sh.tmpl, krib/templates/krib-get-masters.sh.tmpl, krib/templates/krib-haproxy.cfg.tmpl, krib/templates/krib-kubeadm.cfg.tmpl, krib/templates/krib-skip-if-not-master.tmpl
Hi guys, 
In our environment, we have different hardware for masters vs workers, so we don't necessarily want the workers to self-elect to mastership. However, like all good geeks, we're lazy, and we want to be able to "select all" machines and reinstall the cluster with one click.
To this end, here's a PR which introduces 2 optional parameters for "selective mastership" (disabled by default). If `krib/selective-mastership` is **true** (the default is false), then a machine will skip etc/k8s mastership election unless `krib/i-am-master` is also **true** (again, the default is false).
Cheers!
D
=> Optional selective mastership

krib/tasks/krib-dev-reset.yaml, krib/templates/krib-config.sh.tmpl
Hi guys,
Here's a mini-PR.. I've found myself still consistently hitting races when resetting the cluster, even at `$RANDOM % 20`. So I bumped the RANDOM range to 25, and so far, so good. I also added the random sleep to `krib-config.sh.tmpl`, since I saw races there too (_I have a workflow for "soft" reinstalling a cluster, without an OS rebuild, which I'll be PRing soon - the race is more evident there_)
Cheers!
D
=> Increase random sleep from 5 to 25 sec

krib/templates/krib-kubeadm.cfg.tmpl
Hi,
Here's another small issue I stumbled across, and I could use some input. I have a workflow to re-install cluster (without reinstalling OS). The workflow resets the cluster (using `krib-dev-reset`), and then wipes all the relevant data from machine OS. Then I re-install.
Every time I re-installed though, kubeadm would fail to create a cluster, and I found that it was because kubeadm was using the cluster VIP IP, but defaulting to port 6443 (vs 8443, the API VIP port).
The problem was intermittent, because on a small cluster, the host running the template might be the same host which achieved keepalived master status, in which case it _would_ be listening on port 6443 and 8443.
This PR fixes the issue, on both a traditional install and a "soft" install, so I feel as if it's a …
=> Correctly use HA cluster endpoint (WIP - input requested)

krib/params/metallb-l3-ip-range.yaml, krib/params/metallb-l3-peer-address.yaml, krib/stages/krib-metallb.yaml, krib/tasks/krib-metallb.yaml, krib/templates/krib-metallb.sh.tmpl
Hey guys,
Here's a PR to add optional metallb layer 3 configuration to KRIB. It's built on the existing code to deploy L2, and is working insofar as metallb deploys corrects and stands up BGP its peer (I haven't tested with any services yet)
```
root@cn1:~# kubectl --kubeconfig admin.conf get pods -n metallb-system -o wide
NAME                          READY   STATUS    RESTARTS   AGE     IP               NODE                                  NOMINATED NODE   READINESS GATES
controller-7cd4fb6bff-l27f8   1/1     Running   1          7h40m   10.121.210.194   mn2.kube-cluster.funkypenguin.co.nz   <none>           <none>
speaker-2hjnb                 1/1     Running   1          7h40m   192.168.33.12    mn2.kube-cluster.funkypenguin.co.nz   <none>           <none>
speaker-5l5k2 …
```
=> Add metallb l3

krib/params/metallb-l3-ip-range.yaml, krib/params/metallb-l3-peer-address.yaml, krib/stages/krib-metallb.yaml, krib/tasks/krib-metallb.yaml, krib/templates/krib-metallb.sh.tmpl
The `krib-dev-reset` task wipes all cluster information **from DRP**, but not from the machines themselves. The only way (currently) to "start from scratch" is to reinstall the machine's base OS. This takes time, and makes quick iterations painful. This PR adds a step to `krib-dev-reset`, which wipes all traces of the cluster off the machines. The reasoning is that this makes it faster to do a "soft reinstall", starting from installing docker/containerd, and avoiding the whole OS re-install step.
I debated whether to turn this behaviour on/off with a feature flag, but reasoned that if you're wiping the cluster, then you've already declared that you don't want the cluster data retained. Happy to take direction on making this a more user-friendly step if you think it's necessary :)
Cheers! …
=> Wipe machine for cluster reinstall

krib/params/krib-cluster-cri-socket.yaml, krib/params/krib-container-runtime.yaml, krib/params/krib-repo.yaml, krib/stages/krib-runtime-install.yaml, krib/tasks/containerd-install.yaml, krib/tasks/krib-runtime-install.yaml, krib/templates/containerd-install.sh.tmpl, krib/templates/etcd-config.sh.tmpl, krib/templates/krib-kubeadm.cfg.tmpl, krib/templates/krib-runtime-install.sh.tmpl, krib/templates/kubernetes-install.sh.tmpl, krib/workflows/krib-soft-install-cluster.yaml
Hey guys, this is a follow-on from my previous PR re adding containerd as a runtime. This PR includes the containerd PR (because there's some crossover in the downloading of source files). Let me know if this is a problem.
Minus the containerd changes (when the earlier PR is merged), this PR simply adds a conditional to test whether the operator has pre-staged a HTTP/HTTPS repo with the necessary install content. In my case, this saves me 1.4GB of downloads (7 x 200MB) every time I re-install my cluster (it's been 20-30 times today)
Cheers! :)
D
=> Add optional local repo to speed up re-installations

krib/params/krib-cluster-cri-socket.yaml, krib/params/krib-container-runtime.yaml, krib/params/krib-repo.yaml, krib/stages/krib-runtime-install.yaml, krib/tasks/containerd-install.yaml, krib/tasks/krib-runtime-install.yaml, krib/templates/containerd-install.sh.tmpl, krib/templates/krib-kubeadm.cfg.tmpl, krib/templates/krib-runtime-install.sh.tmpl, krib/workflows/krib-soft-install-cluster.yaml
Hey guys,
Here's a PR to implement an alternative container runtime in KRIB (thanks @galthaus for the idea).
I also added (because it was necessary to test):
1. A workflow to "soft-reinstall" a cluster (without an OS rebuild)
2. The beginning of a feature (in an upcoming PR), which introduces the `krib/repo` param, allowing an operator to maintain a local copy of source files, avoiding annoying delays while rebuilding.
3. A fix to the ETC HA PR from a few days ago, because my "if" statement with multiple conditions was invalid (it's now valid)
I've tested this against both containerd and docker, on a full re-install and a "soft" reinstall.
Cheers!
D
=> Add containerd alternative (and fix a bug)

krib/._Documentation.meta, krib/params/krib-ignore-preflight-errors.yaml, krib/templates/krib-config.sh.tmpl
This allows you to do testing that is blocked by the preflight checks.
also, updates the docs
=> add ability to ignore preflight errors, streamline docs

content/tasks/enforce-sledgehammer.yaml
Current check of `if .Param "sledgehammer/enforce"` always passed since the Param exists in community content.
Modify the check to use `if eq (.Param "sledgehammer/enforce" true`.
=> Change 'if' to use 'eq ... true' check

krib/templates/krib-metallb.sh.tmpl
Hey guys,
Felt like this would be a good default, for safety reasons. Basically, prevent metallb from using the first or last IP in a block (10.0.0.0/32, or 10.0.0.255/32, for example)
Cheers!
D
=> Avoid buggy ips by default in metallb

krib/params/krib-log-target-gelf.yaml, krib/params/krib-log-target-syslog.yaml, krib/stages/krib-logging.yaml, krib/tasks/krib-logging-fluent-bit.yaml, krib/templates/krib-ingress-nginx-tillerless.sh.tmpl, krib/templates/krib-metallb.sh.tmpl, krib/templates/logging-fluent-bit.sh.tmpl, krib/templates/logging-fluent-bit.yaml.tmpl
Hey guys,
This PR introduces a fluent-bit implementation based on https://vzurczak.wordpress.com/?p=781, which details a simple design to export all Kubernetes logs to a graylog instance (ideally, off-cluster, although it could be within the cluster).
The changes are implemented as a standalone stage, task, templates, etc, and don't impact any existing workflow unless they're explicitly configured. 
The PR has also accidentally attracted 2 minor bugfixes, one to the metallb implementation, and one to the nginx-ingress deployment.
Cheers!
D
=> Add fluent-bit GELF logging

krib/params/provider-calico-config.yaml, krib/templates/krib-config.sh.tmpl
Hey guys,
A quick one - in a multi-NIC kube deployment, calico auto-selects which NIC to use, and occasionally gets it wrong. This PR does the following:
1. Updates Calico from 3.6 to 3.8
2. Adds config to avoid NetworkManager interference (if enabled)
3. Tells Calico to prefer the NIC which can reach 1.1.1.1, rather than the simplistic (numerical, I think) method calico uses by default. Has no effect on a single-NIC deployment.
Cheers!
D
=> Improve calico

krib/params/krib-ingress-nginx-mandatory.yaml, krib/params/krib-ingress-nginx-publish-ip.yaml, krib/params/provider-calico-config.yaml, krib/templates/krib-config.sh.tmpl, krib/templates/krib-ingress-nginx-tillerless.sh.tmpl
Another optional improvement to nginx-ingress... when if you set the `krib/ingress-nginx-publish-ip` param, then we'll specify `--publish-status-address` to the nginx ingress controller. This is helpful when the IP which the ingress _thinks_ it gets (i.e., from MetalLB) is not the IP the whole world would use.
In my use-case, for example, I assign RFC1918-private IPs via metallb, and perform 1:1 nat on a firewall. However, ExternalDns needs to see my real-world IP as the IP of the ingress, in order to correctly publish external DNS records.
This is an opt-in param, and is also intended to be used with dual nginx ingresses (one called "nginx-external") if the dual-ingress config is opted into as well.
Cheers!
D
=> Optional publish ip for nginx ingress

krib/templates/consul-server.json.tmpl
Finally, a small PR from me!
I noticed that consul is a little too noisy in the logging department by default, so this PR sets it to a sane level. Debuggers could always manually tweak it on local nodes if the need arose :)
D
=> Set sane consul log level

content/bootenvs/ubuntu-18.04-arm64-hwe.yml, content/bootenvs/ubuntu-18.04.yml
- adds amd64 and arm64 Ubuntu 18.04.3 bootenvs to DRP Community Content
=> Add Ubuntu 18.04.3 BootEnv

rancheros/bootenvs/rancheros-disk.yaml, rancheros/bootenvs/rancheros-latest.yaml, rancheros/tasks/rancher-install.yaml, rancheros/tasks/rancher-join-cluster.yaml, rancheros/tasks/rancheros-install.yaml, rancheros/tasks/rancheros-wipe-disks.yaml, rancheros/templates/rancheros-cloud-init.tmpl, rancheros/templates/rancheros-example-state.tmpl, rancheros/workflows/rancher-server-live.yaml, rancheros/workflows/rancher-worker-node-live.yaml
As of now it is hardcoded for sda.
Using the parameter operating-system-disk if available.
Also updating to v1.5.3.
=> Make rancheros operating disk configurable + rancheros v1.5.3

validation/templates/validation-lib.tmpl
Now if you call the `validate_machine_name_dns_by_ip`  using an optional param
of a hostname it will use that, otherwise it defaults to using the Machine.Name
=> made dns call in validation lib more dynamic

coreos/templates/basic-ign.tmpl, task-library/templates/drpcli-init.service.tmpl, task-library/templates/drpcli-init.sysv.tmpl
Instead, the runner will do it when asked to reset or ppowercycle the box.
This change is needed because Runnable applies across all contexts,
and we don't want to interfere with a context that may be managing
power on the real system.
=> Stop marking machines as not runnable on shutdown.

validation/._Documentation.meta, validation/params/validate-nic-counts.yaml, validation/params/validate-nic-required-up.yaml, validation/tasks/validate-nic-counts.yaml
Move the validate nic count/up pieces to the Validation content pack.
Adds two params to control the NIC Count and the UP link check count.
- validate/nic-counts
- validate/nic-required-up
Default values if not specified are 2 and 2.
=> Move validate nic counts to validation

krib/params/docker-version.yaml, krib/params/etcd-version.yaml, krib/params/krib-cluster-cni-version.yaml, krib/params/krib-cluster-crictl-version.yaml, krib/params/krib-cluster-kubernetes-version.yaml, krib/params/provider-calico-config.yaml, krib/templates/docker-install.sh.tmpl, krib/templates/krib-dashboard.sh.tmpl, krib/templates/krib-lib.sh.tmpl, task-library/templates/download-tools.tmpl
update:
docker 19.03
etcd 3.4.1
cni 0.8.2
crictl 1.16.0
kubernetes 1.15.4
calico 3.9
cleanup:
more reliable docker download
dashboard re-apply of serviceaccount removed (previous dashboard token sourced; required pod restart)
=> Update versions + cleanup

task-library/templates/network-lldp-start.sh.tmpl
ip -o link returns a list of all network links, some of which may include a portion with @ followed by the parent interface. This is filtered out to be properly passed to ip link set dev $intf up, otherwise it will err.
=> Filter out content after @ from ip -o link

task-library/params/cluster-machines.yaml
workaround for issue #407 until we update the code to use the more complete object data
=> workaround: dont enforce full object spec during migration

content/bootenvs/fedora-31.yml, content/params/kickstart-base-packages.yaml, content/stages/fedora-31.yml, content/templates/centos-7.ks.tmpl, content/templates/select-kickseed.tmpl, task-library/workflows/fedora-base.yaml
This chgange adds support for Fedora 31 x86_64
This change also introduces a new param called kickstart-base-packages
Fixes: rackn/provision-server#182
=> Adding fedora 31 bootenv

task-library/tasks/bootstrap-lock.yaml
position so that edge-lab and multi-site demo can start using shared code
other generic bootstrap tasks will eventually follow.
=> bootstrap lock is good practice (share code)

content/bootenvs/ubuntu-18.04-arm64-hwe.yml, content/bootenvs/ubuntu-18.04.yml
- updates from `.3.` to `.4` bootenv
=> Ubuntu 18.04.4 (Bionic Beaver) update

task-library/tasks/ansible-join-up.yaml
in testing ansible join-up, discovered need to make sure that this task is idempotent.
this change will test to see if the drpcli service is already running and skip the tasks if it is.
=> enhance: idempotent check to make sure we don't re-run join-up

krib/workflows/krib-install-cluster.yaml, krib/workflows/krib-live-cluster.yaml
Helm v3 is available in Edge Lab, it needs to be ported to KRIB.
Until it's ported, do not use helm in the default k8s install workflows.
=> workaround: remove helm until updated to v3

burnin/params/burnin-cpumem-memory-reserve.yml, burnin/tasks/cpumem_stress.yml
Sledgehammer is in-memory OS and needs a reserve.  Previous 128M/Proc
was sufficient.  Sledgehammer has grown and needs more.  Add parameter
to allow tweaks in the future.  Update default to 256M.
=> fix(burnin): add cpu reserve to allow for tweaking memory usage in test.

krib/._RequiredFeatures.meta, krib/tasks/krib-dev-hard-reset.yaml, krib/tasks/krib-dev-reset.yaml
finally removed unsafe reset hack and moved to use correct ExtraClaims approach.
old method would NOT work because of the RS_PROXY behavior of drpcli in v4 versions.
Change will require 4x DRP w/ ExtraClaims support (which is added as a required feature in the meta data)
=> remove unsafe hack and use ExtraClaims instead. 

chef-bootstrap/content/stages/chef-bootstrap.yaml, chef-bootstrap/content/tasks/chef-bootstrap-configure.yaml, chef-bootstrap/content/tasks/chef-bootstrap-setup.yaml
I just noticed that all task templates are rendered at start which
means we can't have a machine reaching the previously defined
chef-bootstrap-configure task without "chef-bootstrap/node_name" being
defined.
Because of the that we need to have a separate task which takes care of
defining that, and in the future other, parameter(s).
Signed-off-by: Manuel Torrinha <manuel.torrinha@tecnico.ulisboa.pt>
=> Creates a new setup task for chef-bootstrap

chef-bootstrap/content/params/chef-bootstrap.chef_channel.yaml, chef-bootstrap/content/params/chef-bootstrap.chef_version.yaml, chef-bootstrap/content/tasks/chef-bootstrap-install.yaml, chef-bootstrap/content/templates/chef-bootstrap-install.sh.tmpl
Adds two new parameters:
- "chef-bootstrap/chef_channel"
- "chef-bootstrap/chef_version"
"chef-bootstrap/chef_channel" can be usually one of
- "stable"
- "current"
"chef-bootstrap/chef_version" is the Chef version you want to install
in the semver form `x.y.z`, it supports partial versioning, i.e:
- if you want the highest available 14 version you can just specify
as "14"
- if you want the highest available 14.8 version you can specify as
"14.8"
Also adds a missing error_exit function in the install template
Signed-off-by: Manuel Torrinha <manuel.torrinha@tecnico.ulisboa.pt>
=> Add Chef version and channel specification

content/._RequiredFeatures.meta, content/bootenvs/centos-7.6.1810.yml, content/bootenvs/centos-7.7.1908.yml, content/bootenvs/centos-7.yml, content/bootenvs/discovery.yml, content/bootenvs/sledgehammer.yml, content/bootenvs/ubuntu-16.04.yml, content/bootenvs/ubuntu-18.04.yml, content/templates/grub-secure.tmpl, sledgehammer-builder/bootenvs/build-sledgehammer.yaml, sledgehammer-builder/tasks/sledgehammer-stage-bits.yaml
WIP -- do not pull until the corresponding PR has been merged into dr-provision.
This pull request updates Sledgehammer and the CentOS install bootenvs to be compatible with UEFI Secure Boot.  Making Ubuntu and Debian compatible will require further effort, as their install ISOs do not contain signed bootloaders that can netboot.
=> Preliminary uefi secure boot support

integrations/docker-context/ansible-dockerfile, integrations/docker-context/runner-dockerfile, integrations/docker-context/terraform-dockerfile
when building docker image, don't relying on local DRPCLI copy
this code fixes the docker build in a sustainable way
it downloads a known good DRPCLI
then uses that to download the latest stable DRPCLI
future enhancement possible to allow environmental variables
=> fix(content-dockerfile): download cli 

flash/tasks/dell-firmware-flash-list.yml, go.sum
By treating rc5 as ignore, we can have flash lists that work
on extra pieces of hardware that are missing in some models.
=> fix(flash): dell-flash-list treat rc 5 as ignore.

flash/tasks/dell-firmware-flash-list.yml
This allows missing hardware to be skipped and the flash
list can cover more variants.
=> fix(flash): dell flash list - skip rc 5

flash/tasks/lenovo-firmware-flash-list.yml
Use the usb attach script to see if it can be used to handle test of up
=> fix(flash): mc info can return before usb available on lenovo gear.

flash/tasks/hpe-firmware-flash-list.yml
This ignores set -e for choosing a setup script and then fails
when missing.
=> fix(flash): hpe setup chooser shoud not fail because of set -e

content/bootenvs/discovery.yml
getent hosts during Sledgehammer startup was not filtering out
localhost entries properly, which could (in combination with other
issues) lead to the system getting a hostname of
`localhost\nlocalhost`, which would wig out the rest of the machine
name generation process.  Fixing thios at the point it was broken
would require a respin of Sledgeahmmer, so in the meantime work around
it in start-up.sh in the discover bootenv.
=> fix(discoverName): Name generation during discovery was broken.

content/bootenvs/centos-7.yml, content/bootenvs/debian-8.yml, content/bootenvs/debian-9.yml, content/bootenvs/ubuntu-18.04.yml
Bumped Debian 8 to 8.11.1
Bumped CentOS 7 to build 2003
Bumped Debian 9 to 9.12
Fixed URLs for Ubuntu 18.04
=> fix: Update ISO URLs for all operating systems to current values

content/bootenvs/discovery.yml, content/bootenvs/sledgehammer.yml, content/stages/discover-no-gohai.yaml, content/stages/discover.yaml, content/tasks/set-machine-ip.yaml, content/templates/discovery-common-bootstrap.sh.tmpl, content/templates/reset-workflow.tmpl, sledgehammer-builder/bootenvs/build-sledgehammer.yaml, sledgehammer-builder/params/sledgehammer.extra-ifs.yaml, sledgehammer-builder/stages/sledgehammer-build.yaml, sledgehammer-builder/tasks/sledgehammer-stage-bits.yaml
This refactors the discovery and join-up scripts to use a variety
of methods to determine what machine UUID matches the machine they
are running on.  It also refactors the code implementing the discovery
methods out to its own script for ease of ongoing maintenance.
The discovery methods are:
* Whoami
* MAC address matching
* Kernel command line.
* Machine-local saved UUID
* Hostname matching.
Note the lack of address based matching -- experience at one of our
largest customers has taught us that IP based matching cannot be relied upon.
This also refrains from setting the machine Address on machine creation,
and includes a task (that is included in the base discover stage) that uses
the same logic our DHCP server uses to fix up the Address field in the face
of oversubscribed DHCP address …
=> feat(whoami): Refactor discovery scripts to use whoami if present

.gitignore, task-library/tasks/bootstrap-contexts.yaml, task-library/tasks/network-firewall.yaml
Only tested Cetnos8 and Ubuntu in #502,
This patch catches tests on Centos7 which don't include DNF
So added yum install dnf to install the new installer.
=> fix(task-library): Centos7 needs DNF installed

edge-lab/tasks/edge-lab-bootstrap-nfs.yaml, edge-lab/templates/k3s-install.sh.tmpl
k3s needs local storage for overlayfs to work correctly.  This will
attempt to mount USB storage (it is destructive).  This will use
the local SD card for the rpi if nothing else is present.
=> fix(edge-lab): Fix nfs exporting.  Add local storage of SD or USB

content/bootenvs/centos-7.6.1810.yml, content/bootenvs/centos-7.7.1908.yml, content/bootenvs/centos-7.yml, content/bootenvs/fedora-31.yml, content/bootenvs/ubuntu-16.04.yml, content/bootenvs/ubuntu-18.04.yml, sledgehammer-builder/bootenvs/build-sledgehammer.yaml
OK, this doesn't really add secure boot support on arm64, mostly due
to my vms having no way of actually testing it.  Instead, it fixes up
the paths that we serve grub.cfg on for secure boot to work on arm64
as well as amd64, and arrange to use the built-in grub binary (instead
of the shim loader, which crashes qemu right now)
This also removes ISO information frim the sledgehanner builder
bootenv, as it should just be tracking whatever the current version of
centos is instead of pinning it at centos 7.6
=> fix(secureBoot): Fix up boot for UEFI Secure Boot on arm64

.gitignore, edge-lab/._Documentation.meta, edge-lab/params/edge-lab-mount-devices.yaml, edge-lab/params/k3s-admin-conf.yaml, edge-lab/templates/k3s-install.sh.tmpl
This expands on the approach from @galthaus but removes the hard coded paths in favor of pulling from an array defined as a param.  It also allow for more error detection so that a bad mount will not break the logic (but k3s install tests for the mounts later).  
This approach will allow operators to override the default order and type.
For now, the k3s install still relies on a specific path, but that could be split out and parameterized in the future.  If the storage approach is generally useful, this could be refactored as a stand alone task and pulled into common libraries.
=> refactor(edge-lab): expand storage attach logic to use array of inputs

edge-lab/params/edge-lab-dashboard-token.yaml
it's handy to have this URL present as a link.
=> doc(edgelab): turn URL into link

integrations/docker-context/runner-dockerfile
...so we can create rsa keys in the runner context
this is required if we want to run the rsa-key-create task inside of the runner context
=> refactor(contexts): runner context should include keygen

task-library/tasks/ansible-join-up.yaml
code was assuming that task only started after SSH was available.
this allows the task to wait until SSH come online using the normal Ansible mechanism
also - remove gratuitous icon setting calls.
=> refactor(task-library): ansible join-up needs to wait for connection

content/tasks/erase-hard-disks-for-os-install.yaml
This should help with some of the cleaning up of VMWare VSAN
partitions.  It is not guaranteed, but should clear more spots
that the dd might miss.  Running before dd helps get some other
spots.
=> fix(drp-community-content): add wipefs to the cleaning items.

dev-library/params/dev-wait-icons.yaml, dev-library/params/dev-wait-time.yaml, dev-library/tasks/wait-time.yaml
instead of just sleeping
This is helpful when testing dummy workflows because you can see activity in the UX.
Also could be used for API load testing.
=> refactor(dev-library): expand wait time task to include API activity

edge-lab/params/edge-lab-mount-devices.yaml, edge-lab/templates/k3s-install.sh.tmpl
For non-RPi/sledgehammer, we can use the local existing disk when available.
otherwise, use the mounting logic.
most the code change is from indentation shift due to the added if else fi
small tweak to the mount-devices to include a handy comment.
=> refactor(edge-lab): only mount if no local disk

content/bootenvs/discovery.yml, content/bootenvs/sledgehammer.yml, content/params/package-repositories.yaml, sledgehammer-builder/bootenvs/build-sledgehammer.yaml
This version of Sledgehammer no longer releases its DHCP lease when
transitioning from stage1 to stage2.  This was undocumented behaviour
that we don't really want (since we will want another lease a few
seconds later), and not all DHCP servers are good about giving you the
same IP address again when the IP was returned via RELEASE.
=> fix(sledgehammer): Bump sledgehammer to fix DHCP RELEASE issue.

content/bootenvs/discovery.yml, content/bootenvs/sledgehammer.yml, sledgehammer-builder/bootenvs/build-sledgehammer.yaml, sledgehammer-builder/tasks/sledgehammer-stage-bits.yaml
Upstream lldpd grew an indirect dependency on mysql client libraries.
We removed everything them along with everything that directly or
indirectly depended on them.  Fix this error by picking and choosing
the packages that depend in mysql libraries that we want a little more
carefully.
=> fix(sledgehammer): fix accidental removal of lldpd from Sledgehammer

task-library/params/terraform-plan-action.yaml, task-library/params/terraform-plan-templates.yaml, task-library/params/terraform-tfstate.yaml, task-library/params/terraform-var-machine-ip.yaml, task-library/tasks/terraform-apply.yaml
into core library from multi-site-demo
This task has been tested in multi-site manager and reflects the pattern for using terraform contexts in standard pattern.  It addresses the earlier issue of having to save state to the file API by saving the state as a param on the machine.
Works well with the Ansible-Join.
By design, this is just the task - still needs operators to wrap in a stage for now.
=> refactor(task-library): migrate terraform apply task

task-library/tasks/bootstrap-contexts.yaml
during docker context advanced bootstrap.
if an operator is installing the context plugin then they will want the runner context
we don't want to create this as static content because it will require a license and that will break the task-library for non-context users.
=> refactor(task-library): if missing, create the runner context

content/params/access-keys-global.yaml, content/params/access-keys-shared.yaml, content/stages/ssh-access.yaml, content/tasks/ssh-access.yaml, content/templates/access-keys.sh.tmpl
for pooling, operators of machines will want to add their own access-keys per machine or profile.
this change allows operators to have global and profile level ssh-keys that will ALSO work
to provide access to machines.
By design, this adds new levels.  It does NOT remove or change access-keys.
=> refactor(contents): add multiple scopes for access-keys

content/params/no-proxy.yaml, task-library/templates/download-tools.tmpl
The `download()` function from download-tools is commonly use to download stuff in a multitude of places.
Currently, it would use the proxy if the environment has the HTTP_PROXY-style variables exported. However, those are frequently overridden and notoriously hard to keep track of. We've noticed that it's much cleaner to augment the `download()` function and promote its usage, rather then copy-paste the boilerplate HTTP_PROXY exports and tweak the wget/curl invocations all over the place.
This code aims to isolate its changes to the environment and undo them right after the `download()` function finishes. Three env vars (`http_proxy`, `https_proxy` and `no_proxy`) are checked, memorized and reverted after `download()` finishes.
This code reuses the already existing parameter called …
=> task-library: allow download-tools to use proxy

krib/params/docker-apply-http-proxy.yaml, krib/templates/docker-install.sh.tmpl
Applies HTTP_PROXY and NO_PROXY from proxy-servers and no-proxy env vars permanently to the Docker engine via systemd unit file.
=> krib: docker/apply-http-proxy param to install proxy env vars

krib/templates/krib-metallb.sh.tmpl
Creates missing secrets for metallb based on latest installation instructions.
=> krib: create missing secrets for metallb

krib/templates/krib-config.sh.tmpl, krib/templates/krib-dashboard.sh.tmpl, krib/templates/krib-helm-init.sh.tmpl, krib/templates/krib-ingress-nginx-tillerless.sh.tmpl, krib/templates/krib-ingress-nginx.sh.tmpl, krib/templates/krib-metallb.sh.tmpl, krib/templates/krib-runtime-install.sh.tmpl, krib/templates/krib-runtime-proxy.tmpl
Now the installation depends more on the task-library-provided download() function, which benefits from #552.
Also, MetalLB manifests are updated per newest installation instructions.
=> krib: move to use download() and apply proxy when necessary

content/stages/set-machine-name-from-hostname.yaml, content/tasks/set-hostname.yaml, content/tasks/set-machine-name-from-hostname.yaml, content/templates/set-hostname.sh.tmpl, content/templates/set-machine-name-from-hostname.sh.tmpl
- Sets the Machine object `Name` to value of the Param `hostname` if set
- Modifies the `set-hostname` OS set templates to test if the names match, then do nothing
- Useful for Classify to set parameter `hostname` to a value, then this Stage subsequently can modify the Machine Object to match
=> enhance(drp-community-content): Add Machine name set from 'hostname' Param

vmware-lib/content/contexts/govc.yaml, vmware-lib/content/contexts/vcsa-deploy.yaml
We now publish containers in dockerhub, however, the new container name doesn't match the original context Image name.  This fixes the container name to match the container image in dockerhub.
=> fix(vmware-lib): Change the container context to match dockerhub images

dev-library/tasks/wait-time.yaml
minor fix: corrects bug in load generator exposed when new machines don't have icon/color set.
=> bug(dev-library): handle no meta data case for load generator

cloud-wrappers/templates/cloud-provision-reference.tf.tmpl
in the range loop, the new line was required to keep the items from stringing together.
terraform syntax required each pair on a new line
=> bug(cloud-wrapper): needed new line in loop

cloud-wrappers/._Prerequisites.meta
very minor check since <4.4 content has conflicting params
=> refactor(cloud-wrapper): include version requirement in prereq

task-library/params/cluster-profile.yaml, task-library/tasks/bootstrap-contexts.yaml
always planned to switch to podman, but docker was having networking issues w/ Centos8 nftables so I accelerated the timetable and pulled it out.
relatively minimal updates (except now it works better)
=> refactor(task-library): change from docker to podman in context bootstrap

sledgehammer-builder/tasks/sledgehammer-create-stage-1.yaml
Certain custom nic drivers require it to load, and it is small and
otherwise harmless.
=> fix(Sledgehammer): Add the mtd subsystem drivers to stage1.

content/bootenvs/debian-10.yml, content/bootenvs/debian-8.yml, content/params/package-repositories.yaml, content/stages/debian-10-install.yaml, content/tasks/debian-drp-only-repos.yaml, content/templates/deb10-net-seed.tmpl, content/templates/debian-drp-only-repos.sh.tmpl, content/templates/select-kickseed.tmpl, content/workflows/debian-base.yaml
Adds new workflow and bootenv for Debian 10
Fixes errors in previous Debian bootenvs
Add ubuntu-base like workflow for Debian 10
Only works for Network installs, could not find a way to do off-line installs due to limitations with the Debian Installer
=> feat(content): Debian 10 Support

task-library/params/dr-server-install-version.yaml, task-library/tasks/dr-server-install.yaml
and install from online sources
dr-install had been exclusively for dev testing using uploaded install.sh & zip.
this change allows it to pull available versions from the internet also (default)
installation of license is very helpful for multi-site manager installs
includes automatically adding the new endpoint the the license
=> refactor(task-library): update dr-install to pull license 

os-other/bootenvs/rhel-server-7-install.yaml, os-other/bootenvs/rhel-server-8-boot-install.yaml, os-other/bootenvs/rhel-server-8-dvd-install.yaml
Add RackN controlled S3 bucket for os-other images which are Linux
based. Basically adds support for RHEL 7 and 8 installers.
The ISOs are currently publicly available, but can be license
restricted in the future.
=> feat(os-other): Add IsoUrl for Linux installers in os-other

content/templates/setup.tmpl
- use of the `<<<` redirect is not valid on ESXi BusyBox shell
- move to using a more generic construct that is compatible
Results in error on ESXi if run with `<<<` as:
```
-sh: syntax error: unexpected redirection
```
Testing on ESXi:
```
[root@r3r6-u03:~] _add_path=/foo/bar
[root@r3r6-u03:~] grep -q ":$_add_path" <<< ":$PATH:" || export PATH="$PATH:$_add_path"
-sh: syntax error: unexpected redirection
[root@r3r6-u03:~] echo ":$PATH:" | grep -q ":$_add_path" || export PATH="$PATH:$_add_path"
[root@r3r6-u03:~] echo $PATH
/bin:/sbin:/foo/bar
```
=> bug(drp-community-content): Fix setup.tmpl '<<<' redirect breaks ESXi shell

sledgehammer-builder/tasks/sledgehammer-place-stage1-assets.yaml
The default number of retries (10) means that most switchports
which have STP enabled will fail. Increasing the count to 65
should allow most timeouts (up to about 70s) to expire while
attempting to download the second stage. This should have no
impact on non-STP ports, or ports where STP "portfast" are
enabled as the kernel takes a few seconds to complete other
tasks before the 2nd stage download is attempted.
=> fix(sledgehamer-builder): Increase wget retry count for STP

content/tasks/fix-uefi-boot-order.yaml
- fixes the remove boot current boot order to remove instead of prepend to current, which causes double current
- fix typo `efivootmgr` to `efibootmgr`
=> fix(drp-community-content): Fix uefi boot; remove current boot number

task-library/tasks/terraform-apply.yaml
this is a very sad hack because Hashicorp TF v0.13 cannot resolve plans if it thinks they are older format EVEN IF THEY ARE NOT.
=> fix(task-library): terraform 0.13 breaks on legacy syntax, provide upgrade

cloud-wrappers/tasks/cloud-validate.yaml, task-library/tasks/ansible-join-up.yaml
handle intermittent failures on Ansible Join-Up script.
basically checks for pids and does a retry if missing.
also fails more obviously if the pids don't exist instead of leaving system waiting forever.
also, verify that all tags for linode are >2 letters
=>  fix(task-lib): add retry for joinup to handle intermittent failures

integrations/docker-context/ansible-dockerfile, integrations/docker-context/runner-dockerfile, integrations/docker-context/terraform-dockerfile
needed the pooling CLI calls in the runner.
=> fix(contexts-runners): update pull to use v44 DRPCLI

content/bootenvs/debian-10.yml, content/params/debian-buster-netcfg.yaml
Debian 10 (Buster) _preseed_ completely ignores any of the `netcfg/*` configuration stanzas.  Some conventional wisdom says to set the Kernel arguments with `priority=high` or `priority=critical`.  Neither of these worked.  After a dozen different suggested methods, the only one that seems to work is explicitly set the `netcfg/*` values on the Kernel argument/options.
It has worked in the past because by default, a single NIC system will revert to DHCP for network configuration.  If the system has multiple NICs in it, then the current _bootenv_ would fail to autoselect, and prompt the operator to specify which NIC to use for the installer network interface.
This PR:
- Adds new Param exclusively for Debian 10 (Buster) named `debian-buster-netcfg`, with default to auto config NIC
- Sets …
=> fix(debian-10): Fix Debian Buster BootEnv for netcfg

sledgehammer-builder/bootenvs/build-sledgehammer.yaml, sledgehammer-builder/params/sledgehammer-default-python.yaml, sledgehammer-builder/tasks/sledgehammer-prepare-for-image-creation.yaml
This also adds an extra dependency that the Dell firmware update process
requires.  Still needs testing on an HP box.
=> feat(sledge8): Update cent8 sledgehammer to use python2 by default.

task-library/tasks/terraform-apply.yaml
When they came out with 0.13.1 it exposed my overly optimistic regex
=> bug(task-library): fix overly restrictive regex in Terraform version check

task-library/params/ansible-playbooks.yaml, task-library/tasks/ansible-playbooks-local.yaml
but it was not defined.
this makes the ansible/playbooks param (required by ansible-playbooks-local) into a defined param instead of relaying on operator to defined it as an adhoc param.
Added documentation to explain the options and format of the param.
=> fix(task-library): ansible-playbooks-local needed param

task-library/params/ansible-playbooks.yaml, task-library/tasks/ansible-inventory.yaml, task-library/tasks/ansible-playbooks-local.yaml, task-library/templates/ansible-playbooks-test-playbook.yaml.tmpl
allow playbooks-local to use templates in addition to github playbooks.  adding templates in addition to git repos makes it easier to use simple Ansible plays inside of workflows without external dependencies
this change includes a DEFAULT TEMPLATE so that it's very easy and reliable to test the task without having to figure out a all the param settings!  this should make it much easier for new users to explore this task
also, cleaned up the task so that it was much more robust by adding protections for missing values and checks.
=> ferature(task-library): ansible-playbooks-local can use templates

content/bootenvs/discovery.yml, content/bootenvs/sledgehammer.yml, content/profiles/sledgehammer-0b8f38aeecc5a40f915758d9af47102fee6fb83e.yaml
This adds the increased timeouts for wget back to the sledgehammer
stage 1 initramfs.
It also adds an override for a centos 8 based Sledgehammer.  This will
become the default version of Sledgehammer in a future release of
Rebar.
=> fix(sledgehammer): Add back increased wget timeouts.

integrations/docker-context/ansible-dockerfile, integrations/docker-context/runner-dockerfile, integrations/docker-context/terraform-dockerfile, integrations/docker-context/test-build.sh
update the containers to use v4.5 CLI
removed the broken code that was supposed to pull latest but was not - we'll bump the CLI version via patch instead.
also, added a short test script that can be used to build the containers locally to test that they all work.
=> refactor(task-library): update docker-contexts to use v4.5 cli

chef-bootstrap/content/templates/chef-bootstrap-configure.sh.tmpl, chef-bootstrap/content/templates/chef-bootstrap.etc.encrypted.data.bag.secret.tmpl, chef-bootstrap/content/templates/chef-bootstrap.etc.first-boot.json.tmpl, chef-bootstrap/content/templates/chef-bootstrap.etc.user.pem.tmpl
The checker since go v1.14 clashes with the way the condition was previously declared.
see [release notes](https://golang.org/doc/go1.14#text/template) for more info
=> Fixes go template syntax

image-builder/templates/image-builder-cleanup.sh.tmpl
The new-ish "drp-agent" pieces place configuration information in `/var/lib/drp-agent` directory.
This removes those in the image-builder cleanup pass.
=> enhance(image-builder): Cleanup new agent configuration data

image-builder/._Documentation.meta, image-builder/._Prerequisites.meta, image-builder/params/image-builder-post-builder-flexiflow.yaml, image-builder/params/image-builder-pre-builder-flexiflow.yaml, image-builder/stages/image-builder-capture.yaml, image-builder/stages/image-builder-linux.yaml, image-builder/stages/image-builder-post-builder-flexiflow.yaml, image-builder/stages/image-builder-pre-builder-flexiflow.yaml, image-builder/workflows/image-builder-centos.yaml, image-builder/workflows/image-builder-centos8.yaml, image-builder/workflows/image-builder-rhel.yaml, image-builder/workflows/image-builder-ubuntu-bionic.yaml
- adds two _Flexiflow_ Task injection points in to the workflows
- moves the capture process to it's own stage, to allow _Flexiflow_ injection after cleanup, but before capture
- adds _Flexiflow_ stages in the following places :
* prior to the `image-builder-linux` stage customizations
* after the `image-builder-linux` stage, and before the `image-builder-capture` stage
=> enhance(image-builder): Add flexiflow capabilities to Image Builder

task-library/tasks/bootstrap-contexts.yaml
- change `bootstrap-contexts` to use `yum` if exists, then fall through to `dnf`
Current package repos have broken dependency chain for installing `dnf` on CentOS 7 and 8.  This allows use of the default package manager (`yum`) if it exists, then tries `dnf` if `yum` is not present.
=> fix(task-library): fix dnf/yum separation for bootstrap-contexts

content/tasks/ssh-access.yaml, content/templates/access-keys.sh.tmpl
These two new parameters allow for the extension of the ssh
config file.  The access-ssh-temmplate allows for complete override
with your own template.  access-ssh-parameters allows for key/value
style replacement of entries in the config file.
=> feat(content): Add access-ssh-parameters and template override

vmware-lib/content/tasks/ansible-vmware-object-rename.yaml
If VSAN is disabled, but `vsanDatastore` rename defined in `esxi/object-rename` playbook would be generated and subsequently fail because there is no VSAN on the cluster.  This fix adds in a set of rules to test conditions like this and disable generating/running the playbook for disabled subsystems.
The first test is based on `esxi/vsan-enabled` - and if set to false, will not generate the VSAN datastore rename playbook.
=> fix(vmware-lib): If VSAN disabled, do not generate playbook for rename

integrations/docker-context/ansible-dockerfile
fix that python3 stopped including pip3.
this was breaking the docker builds
=> fix(integrations): apt update py3-pip to fix docker pip issue

vmware-lib/content/tasks/ovftool-deploy.yaml
If no datastore is specified, then the command output that is generated had an empty line without a backslash continuation.  This fixes that condition.
=> fix(vmware-lib): OVFTool without datastore defined caused invalid cmd generation

content/params/security-debug-block.yaml, content/templates/setup.tmpl
From reviewing our terraform, ansiblie and kubernetes content, I realized that an operator could add code to enable the rs-debug-enable flag and potentially show sensitive information in the job logs.
This provides a security/* param that can override that behavior for administrators that want to block it.
=> feat(content): security flag overrides debug to protect sensitive data

vmware-lib/content/params/esxi-vsan-tag-only.yaml, vmware-lib/content/tasks/govc-vsan-claim-disks.yaml
- test if NODES ends up with an empty list and error out if no nodes identified to tag/claim
- add new `esxi/vsan-tag-only` Param - which only tags disks for VSAN use but does not claim them (VCF use case pattern)
=> enhance(vmware-lib): Test NODES empty, add tag only

cloud-wrappers/params/cloud-provider-icon.yaml, cloud-wrappers/tasks/cloud-inspect.yaml, cloud-wrappers/tasks/cloud-validate.yaml
When provisioning cloud-wrapper against multiple clouds at the same time, it would be helpful to show different Icons instead of generic "cloud" for each one.
=> refactor(cloud-wrapper): use template vars and make icon selection smarter

content/._RequiredFeatures.meta, content/params/network-data-tag.yaml, content/params/network-manage-routes-command.yaml, content/stages/network-manage-routes.yaml, content/tasks/network-manage-routes.yaml, content/templates/convert_ipv4_netmask_to_cidr_prefix.sh.tmpl
Adds new feature to DRP Community Content to allow adding or removing Routes from Linux, ESXi, or MacOS X systems in the same task.  Utilizes the new `network-data` structure to describe network details, including Routes to manipulate.  In addition, the following params control the behavior of the Task:
- `network-data-tag` - defines which structure in `network-data` to get routes from
- `network-manage-routes-command` - defines "add" or "remove" action for route manipulation
Should work with both IPv4 and IPv6 addressing, assuming the underlaying OS Route command support the syntax.  For ESXi, the Network definition is used to dynamically determine if it's an IPv4 or IPv6 route action needed, since ESXi does not know how to parse the address to determine that.
=> enhance(drp-community-content): Add 'network-manage-routes task

classify/templates/classify-base-actions.sh.tmpl, classify/templates/classify-base-tests.sh.tmpl
Fix several typos in classify function names.
=> fix(classify): Fix typos in function names

content/params/network-data-output-type.yaml, content/params/network-data-parser-debug.yaml, content/params/os-identity-system.yaml, content/stages/os-identity.yaml, content/tasks/os-identity.yaml, content/templates/network-data-parser.tmpl, content/templates/os-identity.sh.tmpl, content/templates/simple-params.py.tmpl
Adds template to parse the `network-data` structure and returns an execution environment specific set of Variables and complex data structures.  The environments supported are Shell (bash, sh, zsh, busybox shell, etc.).
The `network-data` structure is parsed with the following rules / order of precedence:
* values from `all` tag
* values from `prov` (provisioning) tag
* values from `prod` (production) tag
* values from the tag defined by the Param `network-data-tag`
In each environment, a variable will be created in the format of `_nd_<KEY>`; where "`<KEY>`" is the original key name found in the `network-data` structure.  For example for an IP address, the variable `_nd_address` would be created with a value.
For each executing environment, a more complex single data structure will be …
=> enhance(drp-community-content): Add 'network-data' parser

content/bootenvs/fedora-31.yml, content/bootenvs/fedora-33.yml, content/stages/fedora-33.yml, task-library/workflows/fedora-33-base.yaml
- adds `Version` string values to the Fedora 31 and 33 BootEnvs
- adds workflow/stages for Fedora 33
=> enhance(drp-community-content): Fix Fedora bootenvs Versions, add f33 workflow

cloud-wrappers/._Prerequisites.meta, cloud-wrappers/contexts/ansible.yaml, cloud-wrappers/contexts/terraform.yaml, cloud-wrappers/stages/cloud-decommission.yaml, cloud-wrappers/stages/cloud-provision.yaml, task-library/tasks/bootstrap-contexts.yaml
Part of the docker-context refactor to have drpcli-runner as a built in context.
This changes cloudwapper and the context bootstrap to rely on that runner instead
=> refactor(cloud-wrappers): switch to using builtin drpcli-runner for tip

cloud-wrappers/params/aws-ami-id.yaml, cloud-wrappers/params/cloud-dmi-hypervisor.yaml, cloud-wrappers/stages/cloud-inspect.yaml, cloud-wrappers/tasks/cloud-cleanup.yaml, cloud-wrappers/tasks/cloud-inspect.yaml, cloud-wrappers/templates/cloud-provision-reference.tf.tmpl, task-library/tasks/bootstrap-contexts.yaml, task-library/tasks/dr-server-install.yaml, task-library/tasks/network-firewall.yaml
updates required so that DRP will install on AWS Linux 2
note: also needs update to install.sh script (will be it's own patch)
included:
1) cloud-wrapper terraform now opens assigned network/ports during provisioning
2) capture the type of hypervisor as a top level param in cloudwrap
3) use AWS Linux 2 by default (instead of Linux 1)
4) make dr-install more resilient
=> feat(task-library): Install dr server on aws

image-builder/tasks/image-install-cloud-init.yaml
Added conditional to detect if OS is debian based, if so devpts gets mounted
a fake tty is made and cloud-init gets installed.
=> fix(image-builder): fixed ubuntu 18 image building

cloud-wrappers/params/cloud-provider.yaml, task-library/tasks/bootstrap-contexts.yaml, tools/cloud-profiles.sh
Also, includes new tool that uploads local cloud credentials into profiles on an endpoint and sets up docker-context.
This is part of making it easier to setup AWS DR-Server for testing
=> fix(task-library): Amazon Linux does not like yum podman now

content/params/gohai-inventory.yaml, content/params/net-interface-config.yaml, content/params/net-interface-topology.yaml, content/stages/discover.yaml
generally this is a no-op; however, it's included in other OS install workflows so I added it for consistency.
also, enable UX clipboard on several items where it's handy
=> feat(content): add network-config to discover

content/tasks/configure-network.yaml
including this stage in `discover-base` makes sense, but Contexts fail when trying to run this task
=> fix(content): configure-network should no-op for contexts

proxmox/content/params/proxmox-debconf-selections-template.yaml, proxmox/content/params/proxmox-package-selections.yaml, proxmox/content/params/proxmox-strip-kernel-packages.yaml, proxmox/content/params/proxmox-strip-kernel.yaml, proxmox/content/tasks/proxmox-buster-installer.yaml, proxmox/content/tasks/proxmox-debconf-set-selections.yaml, proxmox/content/templates/proxmox-debconf-set-selections.tmpl, proxmox/content/workflows/proxmox-buster-install.yaml, proxmox/content/workflows/proxmox-only-install.yaml
Some minor cleanup and enhancements based on community feedback on some issues.
- Move `debconf-set-selections` to an external Template
- Allow override template to be defined for the `debconf-set-selections`
- Allow customization of the Packages selected at Proxmox install time
- Optionally allow stripping the stock Debian kernels (default is False)
- Remove the ToDo notes about setselecions
=> enhance(proxmox): Minor cleanups and new config options.

content/bootenvs/ubuntu-20.04-install.yml, content/bootenvs/ubuntu-20.04.0-install.yml, content/bootenvs/ubuntu-20.04.1-install.yml
Ubuntu 20.04 bootenvs were busted for 20.04.1 - using hard coded ISO path for 20.04 (no patch version).
This PR changes the bootenvs to use a template construct to template render the correct ISO File name.  NOTE that adding ARM based architectures in the future will require using the right template expansion for those SupportedArchitectures.
=> fix(drp-community-content): Fix ubuntu 20.04 ISO kernel options to use template expansion

cloud-wrappers/params/linode-instance-type.yaml, dev-library/params/dev-counter.yaml, dev-library/params/dev-wait-time.yaml, dev-library/tasks/dev-counter.yaml, dev-library/tasks/wait-time.yaml, task-library/tasks/dr-server-install.yaml
also, includes dev-library adds:
1) a task that helps developers count workflows
2) wait can be random 1-9 secs.
=> fix(task-library): zip file logic was reversed

vmware-lib/content/tasks/ovftool-deploy.yaml
... because ovftool has many many hidden flags that have to be magically remapped from the spec/schemaValidate output ... 
- Remap the JSON `“InjectOvfEnv”: true,` to the command line secret hidden bonus round flag `--X:injectOvfEnv`
- add a little more doc enhancement on how to get the OVF spec information out of an OVA (using ovftool)
=> enhance(vmware-lib): Add secret magic hidden command line flag processing

dev-library/params/dev-reboot-workflow.yaml, dev-library/tasks/dev-reboot-workflow.yaml
this was part of Edge-Lab, moving it here makes it more broadly accessible.
this is step one of migrating out of edge-lab
=> refactor(dev-library) start move of reboot workflow to dev-lib

content/bootenvs/ubuntu-20.04-install.yml, content/bootenvs/ubuntu-20.04.0-install.yml, content/bootenvs/ubuntu-20.04.2-install.yml, content/stages/ubuntu-20.04.2.yaml, task-library/workflows/ubuntu-20.04-base.yaml
Adds the minor point release for Ubuntu 20.04.2 to DRP Community Content.  Updates the Task Library workflow to point directly at the `ubuntu-20.04.2-install` Stage.
Includes v4.6 deprecation notice of the Linux install *base* workflows.
=> enhance(drp-community-content): Add Ubuntu 20.04.2 bootenv

content/bootenvs/ubuntu-20.04-install.yml, content/bootenvs/ubuntu-20.04.0-install.yml, content/bootenvs/ubuntu-20.04.1-install.yml, content/bootenvs/ubuntu-20.04.2-install.yml, content/templates/ubuntu-autoinstall-userdata.tmpl
Fixes the Ubuntu 20.04 autoinstall Template to not inject a bad YAML stanza if there are no SSH keys defined on `access-keys`.
Moves the `autoinstall` template to an external template, and each of the Ubuntu 20.04 bootenvs now utilize the external template.
Validated and tested with ssh access-keys set/unset, access-ssh-root-mode set/unset, and storage stanzas set/unset.  YAML rendering is correct in all variations.  Test installs of Ubuntu 20.04.2 successful.
=> fix(drp-community-content): Fix Ubuntu 20.04 SSH keys not present

content/bootenvs/discovery.yml, content/params/discovery-hostname-selector.yaml, content/params/discovery-hostname-template.yaml
Allows the Discovery BootEnv to allow customization to how HOSTNAME and subsequently Machine object Name fields are populated on discovery.
Default behaviors operate exactly as they used to.  Each of the newly customized values was extensively tested to validate that Discovery was successful in all usage scenarios.
Existing DHCP Lease HOSTNAME settings are honored as per previous behavior.
=> enhance(drp-community-content): Allow Discovery to customize how HOSTNAME is handled.

flash/params/flash-manufacturer-override.yml, flash/tasks/flash-discover.yml
Several Dell systems in the wild often have DMI -> System -> Manufacturer not set in the DMI.  This leads to the Flash tools (and likely others) failing to identify and flash the system correctly.  
This provides an override param that can be set to help correct this issue on systems in the field.  There are (hopefully) sufficient warnings in the Param that this is not a good thing to do generally.
The new Param is `flash-manufacturer-override`, which must be set exactly to one of the BASH `case` statement checks found in the `flash-discover` Task.
=> enhance(flash): Provide Manufacturer override

cloud-wrappers/params/cloud-provider.yaml, cloud-wrappers/params/pnap-client-id.yaml, cloud-wrappers/params/pnap-client-secret.yaml, cloud-wrappers/params/pnap-location.yaml, cloud-wrappers/params/pnap-os.yaml, cloud-wrappers/params/pnap-type.yaml, cloud-wrappers/stages/cloud-provision.yaml, cloud-wrappers/tasks/cloud-inspect.yaml, cloud-wrappers/tasks/cloud-validate.yaml, cloud-wrappers/templates/cloud-provision-aws.tf.tmpl, cloud-wrappers/templates/cloud-provision-azure.tf.tmpl, cloud-wrappers/templates/cloud-provision-pnap.tf.tmpl, content/tasks/bootstrap-ssh.yaml, integrations/docker-context/ansible-dockerfile, integrations/docker-context/runner-dockerfile, integrations/docker-context/terraform-dockerfile, integrations/docker-context/test-build.sh, task-library/tasks/ansible-join-up.yaml, task-library/tasks/dr-server-install.yaml, task-library/tasks/terraform-apply.yaml, tools/bundle-and-upload.sh, tools/cloud-profiles.sh
Mainly cleanups to the content packs covering
* bootstrap-ssh updated to add keys (was right approach anyway, but required for HA)
* dr-site-create stage includes required port 8092 so that it cannot be overlooked
* dr-site-create will add SSH keys from access-keys when installing on new server (handy since agent does not run there)
* adding 8092 to param via stage required cleanup of handling ports
* change so cloud wrapper to not require port 8091 (which is not open by default now)
* added Phoenix NAP to test cloud-wrapper on new platform
* updated Ansible and Terraform Contexts to have most recent versions (updated in repo.rackn.io also)
*
=> refactor(content): pre-release cleanups to cloud-wrapper, bootstrap-ssh, dr-server-install

task-library/tasks/dr-server-install.yaml
in v4.6, license check must use cloudia.
=> refactor(task-library): dr-install license check uses rackn.io site

content/bootenvs/rocky-8-install.yaml, content/params/kickstart-base-packages.yaml, content/stages/rocky-8-install.yaml, content/templates/rocky-8.ks.tmpl, content/templates/select-kickseed.tmpl, os-other/workflows/rocky-server-8-dvd-install.yaml
Adds Rocky 8 (_release candidate_) Linux to DRP Community Content and os-other (for workflow).  Rocky 8 has been added to Universal content as well, and it is preferred to use Universal for deployment of this OS.
Tested successfully.
**_WARNING_**
DRP backend `package-repositories` handling has not been added to support Rocky Linux natively.  DRP is currently using CentOS package repositories information for package handling.  This PR does not address `package-repositories`
=> enhance(drp-community-content,os-other): Add Rocky 8 Linux to DRPCC and os-other

content/templates/net-seed.tmpl
Fixes egregious typo in golang template construct for the `net-seed.tmpl` for `ntp-servers` and for `proxy-servers`.
=> fix(drp-community-content): Fix net-seed typo for proxy and ntp-servers

content/workflows/debian-base.yaml
drp-community-content has a drp-agent stage which installs drpcli
running in agent mode,  Replace the reference in the debian-base
workflow to runner-service with drp-agent
=> fix(debian-base): Remove inadvertent dependency on task-library.

cloud-wrappers/workflows/cloud-provision.yaml, os-other/workflows/rhel-server-8-dvd-install.yaml, proxmox/content/workflows/proxmox-buster-install.yaml, proxmox/content/workflows/proxmox-install-and-setup.yaml, task-library/stages/runner-service.yaml, task-library/workflows/discover-joinup.yaml
This switches more things to rely on drp-agent from community
content instead of runner-service in the task library.
=> feat(drp-agent): Switch more things to use drp-agent

content/templates/ubuntu-autoinstall-userdata.tmpl
The Ubuntu autoinstall [schema](https://ubuntu.com/server/docs/install/autoinstall-schema#Schema) dictates that allow-pw is a boolean. Unless we explicitly parse the `access-ssh-root-mode` param, and spit out a boolean, we risk the user crashing the installer by specifying a non-boolean. That consideration aside, `allow-pw` in this context has nothing to do with root - it's applicable to all SSH logins, and so removing it makes more sense than trying to shoehorn a kickstart parameter into an Ubuntu autoinstall (as I discovered to my detriment!)
=> Remove redundant allow-pw option from ubuntu autoinstall

task-library/profiles/bootstrap-drp-endpoint.yaml, task-library/templates/bootstrap-tools.sh.tmpl
Enhances the `bootstrap-tools` Param to be composed, so Operator can append and build up the list of packages to install.
Clean up the documentation.
Remove the `bootstrap-tools` explicitly set in `bootstrap-drp-endpoint`, as it's redundant to the `bootstrap-ipmi` Param/Task which uses the `bootstrap-tools`.
=> enhance(task-library): allow 'bootstrap-tools' to Compose

vmware-lib/content/stages/govc-host-add.yaml, vmware-lib/content/tasks/govc-host-add.yaml, vmware-lib/content/templates/govc-lib.sh.tmpl
Adds ability to enroll an ESXi host in to a Datacenter or Datacenter + Cluster construct.  This pattern uses the correct `contexts` feature capability, and requires the `govc` context be installed on the DRP Endpoint.
Requires the `vmware` plugin `esxi-host-thumbprint` task to set the SHA1 thumbprint.  This should be available in `v4.7.0-alpha00.19` or newer of the vmware plugin.
=> enhance(vmware-lib): Add context host add capability

content/bootenvs/debian-10.yml
Debian 10 (Buster) isn't installing correctly and fails at selecting a mirror. This patch changes the type of ISO that is downloaded where the new ISO contains a mirror inside the ISO.
=> Update the Debian 10 (Buster) iso to use the full image rather than the mini.iso

burnin/params/burnin-disk-max-errors.yml, burnin/tasks/disk_stress.yml
Ditch incremental status updates when running badblocks.  We run them
all in parallel in the background, and status messages are kinda
pointless in that mode.
Expose a param that lets badblocks bail early after a set number of errors.
The default is to have it try to scan everything anyways.
=> fix(burnin): Tweak the disk stress test task.

content/templates/net-seed.tmpl
This fixes the following error message that shows when a machine is provisioned in UEFI mode (note that is already addressed in Debian 10):
This machine's firmware has started the installer in UEFI mode but it looks like there may be existing operating System already installed using BIOS compatiblity mode. If you continue to install Debian in UEFI mode, it might be difficult to reboot the machine into any BIOS-mode operating system later.
If you wish to install UEFI mode and don't care about keeping the ability to boot one of the existing systems, you have the option to force that here. If you wish to keep the option to boot an existing operating system you should choose NOT to force UEFI installtion here.
Force UEFI installation?
=> Fix issue provisioning Debian 8/9 and possible Ubuntu when machine is in UEFI mode.  

tools/windows/AddFiles_WinPE_64/Windows/System32/shutdown.cmd, tools/windows/Build-WinPEx64.cmd, tools/windows/README.md
This script will build a basic WinPE based on the Windows 10 ADK.
It supports adding drivers and additional files to the WinPE image
to enable advanced template execution.
The readme file has been update to include instructions to use the
script.
The shutdown batch file is there to support the remote shutdown and
reboot functionality of the drpcli agent, which is not natively
supported within WinPE.
=> Script to create a WinPE based on Windows ADK 10

os-other/bootenvs/rhel-server-7.7-install.yaml, os-other/bootenvs/rhel-server-7.9-install.yaml, os-other/bootenvs/rhel-server-8-boot-install.yaml, os-other/bootenvs/rhel-server-8-dvd-install.yaml, os-other/bootenvs/rhel-server-8.2-dvd-install.yaml
They should never have been added in the first place.
=> fix(rhel): Remove links to rhel iso files.
